### ISSUE TITLE
[FEATURE REQUEST]: Add Husky

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#1]
**Is your feature request related to a problem? Please describe.**
Add Husky to the project to make pre-commit validations

**Describe the solution you'd like**
The pre-commit should do the following:
- lint the code for errors
- fix the errors (if fixable)
- run prettier fix on the entire project

**Comment by Abbhiishek** [comment]
hey @rajdip-b,

i want to work on this feature

**Comment by rajdip-b** [comment]
@Abbhiishek here you go!

**Comment by Abbhiishek** [comment]
While doing `pnpm install` am getting this error:

`WARN  Installing a dependency from a non-existent directory: D:\optimus prime\keyshade\@nx\js:library`

**Comment by Abbhiishek** [comment]
<img width="462" alt="image" src="https://github.com/keyshade-xyz/keyshade/assets/86338762/94a71013-e880-407f-8939-f0666ea0ee3f">

**Comment by rajdip-b** [comment]
That looks odd. I'll try this once on windows and lyk.

**Comment by rajdip-b** [comment]
Hey @Abbhiishek, I ran it and couldn't find any issues. Mind telling me what command gave you the stack trace error? Also, what's the current RAM on your device?

> WARN  Installing a dependency from a non-existent directory: D:\optimus prime\keyshade\@nx\js:library
This was fixed by removing the `js:library` from `package.json`

**Comment by Abbhiishek** [comment]
hey @rajdip-b,
removing `js:library` from `package.json` resolves the whole issue. 
i am able to pnpm install without any errors.

**Comment by rajdip-b** [comment]
Great to hear! Please do let us know in here if you face any other issues!

**Comment by Abbhiishek** [comment]
hey @rajdip-b i have made the initial setup for husky ... need some insight on the scripts we need to run for precommit.

Looking at the package.json file :

```json
    "lint": "nx run-many -t lint --parallel",
    "lint:api": "nx run api:lint",
    "lint:web": "nx run web:lint",
    "lint:workspace": "nx run workspace:lint",
    "lint:cli": "nx run cli:lint",
    "lint:sdk-node": "nx run sdk-js:lint",
    "lint:fix": "nx run-many -t lint --fix --parallel",
```

I suppose we need to run **lint** and **lint:fix** for every commit right?

**Comment by Abbhiishek** [comment]
I tried running pnpm lint:fix and here are the insights 


       NX   Ran target lint for 7 projects (1s)                                                                                                    
                                                                                                                                                
       With additional flags:                                                                                                                 
           --fix=true                                                                                                                           
                                                                                                                                                
    √    6/7 succeeded [6 read from cache]                                                                                                      
                                                                                                                                                
    ×    1/7 targets failed, including the following:                                                                                           
         - nx run sdk-rust:lint                                                                                                                 

   View structured, searchable error logs at https://nx.app/runs/ecSS0oBnCJ

<img width="201" alt="image" src="https://github.com/keyshade-xyz/keyshade/assets/86338762/77c2ef38-b7e7-4b44-b95e-eefb6acd435a">

It successfully run over these apps 

<img width="298" alt="image" src="https://github.com/keyshade-xyz/keyshade/assets/86338762/39468774-00a5-488c-95cc-648c7977bece">

**Comment by rajdip-b** [comment]
yeah there are some issues with rust currently. i would suggest you make the `lint:fix` command to exclude the rust-sdk module. and then use the `lint:fix` command in husky.

**Comment by kriptonian1** [comment]
Hey @Abbhiishek, how is the progress going

**Comment by Abbhiishek** [comment]
Hey @kriptonian1 i have raise a PR!
