### ISSUE TITLE
Unit tests for `getAllUsers` function

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#10]
**Is your feature request related to a problem? Please describe.**
I would like to have a unit test for the controller and the service for the `getAllUsers` function in the user module.

**Scope of changes**
All changes will occur in `apps/api/user`

1. Service (`user.service.ts`)
![image](https://github.com/keyshade-xyz/keyshade/assets/83924254/cf3d755f-93fb-4a68-9799-b9823317e7ff)
- Make a mock repository call in the `fake.repository.ts` file.
- Add test in `user.service.spec.ts`

2. Controller (`user.controller.ts`)
![image](https://github.com/keyshade-xyz/keyshade/assets/83924254/1c1ad44f-bb6b-45b2-bb1c-eebbff15a8b6)
- Add test in `user.controller.spec.ts`

**Comment by lakshay-saini-au8** [comment]
@rajdip-b would like to work on this

**Comment by rajdip-b** [comment]
Be my guest! @lakshay-saini-au8

**Comment by rajdip-b** [comment]
@lakshay-saini-au8 if you face any issues whatsoever, please ping us on discord. Alternatively, you can also create a thread in there.

**Comment by rajdip-b** [comment]
Hey @lakshay-saini-au8 !! Any progress on this?

**Comment by rajdip-b** [comment]
Fixed by #37
