### ISSUE TITLE
Code refactors

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#104]
## Description

The following issues are detected by the sonarqube lint. They are really minor and are mostly refactor issues.

- [ ] ['@prisma/client' imported multiple times.](https://sonarcloud.io/project/issues?open=AY1bRC1sOjkDSIbCxDfw&id=keyshade-xyz_keyshade)
- [ ] [Merge the functions into one with an additional `forRegisteredUser` flag](https://sonarcloud.io/project/issues?open=AY02ait6yOTN05EC0RYL&id=keyshade-xyz_keyshade)
- [ ] [Replace `as` with upper case format `AS`.](https://sonarcloud.io/project/issues?open=AY02ait2yOTN05EC0RYI&id=keyshade-xyz_keyshade)

**Comment by rajdip-b** [comment]
@SRINJAYDASGUPTA-Git wanna give this a shot? EZPZ

**Comment by SRINJAYDASGUPTA-Git** [comment]
the second issue..... Both the functions are same.... do i just add a boolean `forNonRegisteredUser` ? in the params @rajdip-b

**Comment by rajdip-b** [comment]
> the second task..... Both the functions are same.... do i just add a boolean `forNonRegisteredUser` ? in the params @rajdip-b the first Task, its present on two `Dockerfile` s do change both? (`/apps/api/Dockerfile` & `/apps/web/Dockerfile`)

Yes! go for it

**Comment by SRINJAYDASGUPTA-Git** [comment]
check out the pr @rajdip-b
