### ISSUE TITLE
Make GitHub OAuth optional

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#107]
## The problem

In many scenarios, we want the GitHub OAuth to be optional. Currently its not possible since the application will crash if the github specific oauth keys are not mentioned

## Solution

Make the GitHub OAuth provider check for `GITHUB_CLIENT_ID`, `GITHUB_CLIENT_SECRET` and `GITHUB_CALLBACK_URL`. If any one of them is underfined, we don't want the application to init GitHub OAuth.

Additionally, we would also like the controller in charge of doing github login to send a message that Github log in is not enabled in this environment with a `BadRequestException`

**Comment by rajdip-b** [comment]
@SRINJAYDASGUPTA-Git care to take this one?

**Comment by HarshPatel5940** [comment]
@rajdip-b I would like to work on this if that's fine

**Comment by rajdip-b** [comment]
Sure! go ahead!

**Comment by HarshPatel5940** [comment]
thanks!
