### ISSUE TITLE
SonarQube lint failing due to duplicated lines

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#111]
## Description 

![image](https://github.com/keyshade-xyz/keyshade/assets/83924254/33b32ddb-81c7-47ae-9f99-a5dc59e8ac34)

The CI is currently failing due to duplicated lines in `workspace-role.e2e.spec.ts` files. We would like to reduce the number of duplicated lines < 50. 

### Reports:
- https://sonarcloud.io/component_measures?id=keyshade-xyz_keyshade&metric=new_duplicated_lines_density&selected=keyshade-xyz_keyshade%3Aapps%2Fapi%2Fsrc%2Fapi-key%2Fapi-key.e2e.spec.ts
- https://sonarcloud.io/component_measures?id=keyshade-xyz_keyshade&metric=new_duplicated_lines_density&selected=keyshade-xyz_keyshade%3Aapps%2Fapi%2Fsrc%2Fworkspace-role%2Fworkspace-role.e2e.spec.ts

**Comment by HarshPatel5940** [comment]
@Inigojeevan give this a look, its a good once to get started with. send `/attempt` here if you are interested to work on this.

**Comment by rajdip-b** [comment]
Feel free to drop into our discors channel to have a discussion on this if you want @Inigojeevan !
