### ISSUE TITLE
Optimize dockerfiles

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#113]
## Description

Currently, the Dockerfiles for `web` and `api` are crossing 1GB size. We would like to reduce the final build size so that we get a significant lower build time in out CIs.

The files are:
- `apps/api/Dockerfile`
- `apps/web/Dockerfile`

Things you can do:
- Use a multi-staged build 
- Purge the development dependencies

**Comment by rajdip-b** [comment]
Hey bro @Abbhiishek mind giving this a shot?

**Comment by Abbhiishek** [comment]
sure

**Comment by rajdip-b** [comment]
Awesome bro! @Abbhiishek assigning this to you

**Comment by Abbhiishek** [comment]
I have created a draft for web: 

```yml
# Alpine image
FROM node:20-alpine AS alpine
RUN apk update
RUN apk add --no-cache libc6-compat


# Setup pnpm and turbo on the alpine base
FROM alpine as base
RUN npm install pnpm turbo --global
RUN pnpm config set store-dir ~/.pnpm-store



# Prune projects
FROM base AS pruner
ARG PROJECT


WORKDIR /app
COPY . .
RUN turbo prune --scope=${PROJECT} --docker

# Build the project
FROM base AS builder
ARG PROJECT



WORKDIR /app

# Copy lockfile and package.json's of isolated subworkspace
COPY --from=pruner /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=pruner /app/out/pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY --from=pruner /app/out/json/ .


# First install the dependencies (as they change less often)
RUN --mount=type=cache,id=pnpm,target=~/.pnpm-store pnpm install --frozen-lockfile


# Copy source code of isolated subworkspace
COPY --from=pruner /app/out/full/ .

RUN turbo build --filter=${PROJECT}
RUN --mount=type=cache,id=pnpm,target=~/.pnpm-store pnpm prune --prod --no-optional
RUN rm -rf ./**/*/src



# Final image
FROM alpine AS runner
ARG PROJECT

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nodejs
USER nodejs

WORKDIR /app
COPY --from=builder --chown=nodejs:nodejs /app .
WORKDIR /app/apps/${PROJECT}

ARG PORT=3000
ENV PORT=${PORT}
ENV NODE_ENV=production
EXPOSE ${PORT}

CMD node dist/main

```

I am passing project as web for building the web micro however :( the below mentioned error occured


```
=> ERROR [web pruner 3/3] RUN turbo prune --scope=web --docker                                                                                           0.4s
------
 > [web pruner 3/3] RUN turbo prune --scope=web --docker:
0.382
0.382 Attention:
0.382 Turborepo now collects completely anonymous telemetry regarding usage.
0.382 This information is used to shape the Turborepo roadmap and prioritize features.
0.382 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
0.382 https://turbo.build/repo/docs/telemetry
0.382
0.424   x invalid scope: package web not found
0.424
------
failed to solve: process "/bin/sh -c turbo prune --scope=${PROJECT} --docker" did not complete successfully: exit code: 1

```

**Comment by rajdip-b** [comment]
Yeah actually you got a base very wrong :) You are using `turbo` but this repository is using `nx`

**Comment by Abbhiishek** [comment]
ohhh my bad 🥲! i tried doing it traditionally but there was some path issues i will give it try once again

**Comment by rajdip-b** [comment]
Not an issue my friend!

**Comment by rajdip-b** [comment]
Hey bro @Abbhiishek made any further progress on this?

**Comment by Abbhiishek** [comment]
hey i was able to dockerise but my application is not building correctly. Files are not imported to the container. Still working on this issue. Will keep you updated :)

**Comment by rajdip-b** [comment]
> hey i was able to dockerise but my application is not building correctly. Files are not imported to the container. Still working on this issue. Will keep you updated :)

Wow that's strange, do drop in a thread on discord if you wanna discuss this!

**Comment by Abbhiishek** [comment]
i am giving a try to use https://www.npmjs.com/package/@nx-tools/nx-container plugin.

**Comment by rajdip-b** [comment]
Hey bro, just hold up for a day or 2. We are migrating our project to Turbo. I believe it will be much more easier for you to do so once the migration is done!

**Comment by Abbhiishek** [comment]
turbo 😀

**Comment by Abbhiishek** [comment]
sure

**Comment by rajdip-b** [comment]
@Abbhiishek hey bro! The migration is complete. You can start your work on this.

**Comment by Abbhiishek** [comment]
hey @rajdip-b ,

a general question about the web app microservice. I am referring to this page [here ](https://turbo.build/repo/docs/handbook/deploying-with-docker). According to this each app should also contain a `package.json` file.

```
├── apps
│   ├── docs
│   │   ├── server.js
│   │   └── package.json
│   └── web
│       └── package.json
├── package.json
└── package-lock.json

```

**Comment by rajdip-b** [comment]
@Abbhiishek yes since we now have turbo, every microservice now has its own package.json that has deps specific to that package.

**Comment by Abbhiishek** [comment]
hey @rajdip-b i was able to contain web.
The new build size is 169mb

![image](https://github.com/keyshade-xyz/keyshade/assets/86338762/5456d853-262f-4831-b6fa-7f676d67d9fe)

**Comment by rajdip-b** [comment]
Awesome bro!!!
