### ISSUE TITLE
Create user endpoint

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#13]
**Is your feature request related to a problem? Please describe.**
As an admin, we would like to create an user using the API

**Describe the solution you'd like**
The endpoint will do the following:
- Create a user using their name, email and profile picture (if applicable)
- Set `isActive`, `isOnboardingFinished` and `isAdmin` to false/true as specified by the admin.
- Send out an email to them asking them to log in to their account

The code should live in the `user` module. Also, necessary unit tests are required.

**Comment by Sachinsharma01** [comment]
@rajdip-b looks promising, is it in progress? if not, I would like to contribute

**Comment by rajdip-b** [comment]
Hey @Sachinsharma01! It's still in todo. So feel free to pick this up!

**Comment by Sachinsharma01** [comment]
on it
