### ISSUE TITLE
Add tests for docker build

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#131]
## Description
Whenever changes occur to any of the docker files, we want a CI to run to evaluate the validity of these changes. Right now, we have just 2 docker files:
- `apps/web/Dockerfile`
- `apps/api/Dockerfile`

## Solution

- The CI should run when: 
  1. Changes occur to any of the docker file
  2. Changes are made during a push or in a pull request
- Test for build: Issue a `docker build` command, then check if the image was built successfully

**Comment by rajdip-b** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add tests for docker build](https://trello.com/c/bWmXEe93/21-add-tests-for-docker-build)

**Comment by DhairyaMajmudar** [comment]
/attempt

Taking this up : )
