### ISSUE TITLE
Read `port` dynamically in `api`

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#134]
## Description
![image](https://github.com/keyshade-xyz/keyshade/assets/83924254/de8196ef-aec1-40d9-84d4-f30565acaf0e)

We would like to give users the option to update the port from the environment without needing to alter any code. This will involve changing the `main.ts` and `Dockerfile` files.

## Solution
- [ ] Create an environmental variable named `API_PORT`
- [ ] Add it to `.env.example`
- [ ] In the `main.ts` file, read this environmental variable. If it's not set, default the `port` to `4200`
- [ ] In the `Dockerfile`, update the `EXPOSE 4200` to `EXPOSE ${API_PORT:-4200}`

## Additional context
All the related files are stored under `apps/api`

**Comment by Aditya-Ghosh-27** [comment]
i am solving this issue asap

**Comment by rajdip-b** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Read port dynamically in API](https://trello.com/c/SLhXEH5J/28-read-port-dynamically-in-api)

**Comment by HarshPatel5940** [comment]
@Aditya-Ghosh-27 what are the updates with this issue? Let's get this once completed soon.

**Comment by Aditya-Ghosh-27** [comment]
I have solved the issue, but I am facing issues while pushing it. Some
insights would be helpful
