### ISSUE TITLE
Integrate `pg-boss` for job scheduling

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#138]
## Description
To run jobs in the background as cronjobs jobs, or jobs that might take up significant resources, we would like to use `pg-boss`. This would allow us to harness the power of our database.

This issue focuses on creating the client API for `pg-boss`

Use this article for reference: https://www.npmjs.com/package/pg-boss

## Solution
- Create a separate module and name it `job-handler`. Add a class called `JobHandler` in `job.handler.ts`.
- It should have a constructor that will initialize pg boss.
- It should have a generic function that will do the actual job on our behalf. The signature would be:
  ```typescript
  async <T, V>registerJob(queue: string, callback: (job: V) => T) => T;
  ```
- Export this module globally (take reference from how the `prisma` module is exported globally).

**Comment by rajdip-b** [comment]
@Ratnesh2003 hey bro made any progress on this?

**Comment by rajdip-b** [comment]
This issue is up for grabs again!

**Comment by rajdip-b** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Integrate pg-boss for job scheduling](https://trello.com/c/MCB3cE9W/14-integrate-pg-boss-for-job-scheduling)

**Comment by Allan2000-Git** [comment]
@rajdip-b To confirm, I'll have to create `job-handler` folder in `apps/api/src`, then create `job.handler.ts` file and then create a class JobHandler that handles rest of the task?

**Comment by rajdip-b** [comment]
I think, we won't need all that trouble. You can add `job.handler.ts` directly in `common` module

**Comment by Allan2000-Git** [comment]
/attempt I'd love to work on this issue.
