### ISSUE TITLE
Add more logging to Sentry init

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#145]
## Description
Add more description into the sentry initialization function in `main.ts` to display the configurations it has been launched with. For example, `SENTRY_ORG`.

**Comment by rajdip-b** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add more logging to Sentry init](https://trello.com/c/z7Z8USPQ/24-add-more-logging-to-sentry-init)

**Comment by YuvalBubnovsky** [comment]
/attempt

@rajdip-b Can you guide me to where the appropriate tests are for this? (unit/integration)

**Comment by YuvalBubnovsky** [comment]
Also some points to discuss regarding the implementation here:

1. Sentry ProfilingIntegration is deprecated, should use nodeProfilingIntegration instead
![image](https://github.com/user-attachments/assets/0fd40816-e803-49ef-bdc9-b752768b943f)

2. I feel like a return statement is missing in case one or more env vars are missing for Sentry initialization
3. I think it would be best-practice to wrap around the Sentry initialization in a try-catch block
4. We could add some input validation (for example, if we received a value for SENTRY_TRACES_SAMPLE_RATE, make sure it's a value between 0.0 and 1.0)

Let me know how you feel about this, I can also of course just add something like:
```typescript
    logger.log('Sentry initialized with the following configuration:')
    logger.log(`Sentry Organization: ${process.env.SENTRY_ORG}`)
    logger.log(`Sentry Project: ${process.env.SENTRY_PROJECT}`)
    logger.log(`Sentry Environment: ${sentryEnv}`)
    logger.log(`Sentry Traces Sample Rate: ${tracesSampleRate}`)
    logger.log(`Sentry Profiles Sample Rate: ${profilesSampleRate}`)
    logger.log(`Sentry Debug Mode: ${sentryEnv.startsWith('dev')}`)
```
..and call it a day.

**Comment by rajdip-b** [comment]
1. Yes, it has been quite a few months since I wrote this section. I think you can go ahead and fix the deprecation.
2. The function doesn't return anything in either case. So it won't really matter. If the envs are missing, we don't execute any other lines of code.
3. Agreed
4. Validation is already present, but the range isnt. Feel free to implement that in `src/common/env/snv.schema.ts`
