### ISSUE TITLE
Add project access level

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#154]
## Description
Right now, projects are created in a fashion that, to be visible to someone in the workspace, the member needs to have a role association that has the project associated with it in the `projectIds` array. Similarly, for any external user, the project needs to have `isPublic` set to `true` to access it. 

We would like to have fine-grained control to be able to handle the following type of access to the project:
- Any non-user can access a project (public)
- Any workspace member can access the project (internal)
- Only selected members via role association can access the project (private)

You can think of this scenario as something that GitLab or GitHub promotes to categorize repository access across teams.

## Solution
To implement this, we would like to replace the `isPublic` field of `Project` entity with `accessLevel`. This will be an enum of type `AccessLevel` that will be defined in `schema.prisma`. These would be the enum values and associated authority:
- `GLOBAL`: Anyone in the world can access the project
- `INTERNAL`: Any member in the workspace with `READ_PROJECT` collective authority will be able to access the project
- `PRIVATE`: Only users with role association that has the project's ID in its `projectIds` field will be able to access this project.

**Comment by rajdip-b** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add project access level](https://trello.com/c/S1u3IyM1/35-add-project-access-level)

**Comment by rayaanoidPrime** [comment]
Hi ! I'd like to attempt this one.... also just to be clear about the scope of changes needed for this--- We basically need to change the prisma schema for Project, change the approval , api-key guard , auth logic as well as the logic of all services that touch projects around it and finally the tests right? Please let me know if I missed anything.

**Comment by rajdip-b** [comment]
Yes, that will mostly be all. You will need to add an enum named `ProjectAccessLevel` to prisma schema to store the different access levels. And then link it to the project.

Then you will need to update the `checkAuthorityOverProject` method to make sure you allow/block access to a project accordingly. 

I dont think you will need to change the `api-key` guard file.

**Comment by rajdip-b** [comment]
@rayaanoidPrime I'm refactoring the e2e tests for projects into something more readable. I'll notify you when I merge the code so you can take a pull!
