### ISSUE TITLE
GitLab OAuth

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#155]
Users should be able to log in to our platform using GitLab. When doing so, we should scrape off the following things and persist them in our db:

- avatar
- name
- email

**Comment by rajdip-b** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GitLab OAuth](https://trello.com/c/UCj077RT/38-gitlab-oauth)

**Comment by rajdip-b** [comment]
@HarshPatel5940 @Abbhiishek anyone wants to give this a shot?

**Comment by HarshPatel5940** [comment]
Will do it, as time permits!

**Comment by rajdip-b** [comment]
Sure bro! Not an emergency but a good to have.
