### ISSUE TITLE
Add maximum page size in fetch endpoints

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#160]
## Description
Currently, the endpoints that fetch paginated data does not provide any upper limit to the page size. We need to put a limit to that to make sure we don't burn our API.

## Solution
We would like to add an upper limit to these fetch endpoints, something like this:
```
-take: limit,
+take: Math.min(limit, 30)
```
The maximum items per page should be 30. 

All the controllers in all the modules that have a paginated response will be affected.

**Comment by rajdip-b** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add maximum page size in fetch endpoints](https://trello.com/c/zAoXE3xb/40-add-maximum-page-size-in-fetch-endpoints)

**Comment by aniimessh** [comment]
Can I work on this issue ?

**Comment by rajdip-b** [comment]
Absolutely!

**Comment by rajdip-b** [comment]
Hey bro @aniimessh ! Could you make any progress on this? You could always hit me up if you need help.

**Comment by aniimessh** [comment]
> Hey bro @aniimessh ! Could you make any progress on this? You could always hit me up if you need help.

I am sorry, I am working a little slow I am not professional with backend, so I am researching and working.

**Comment by rajdip-b** [comment]
Sure thing bro!! No worries, just was checking on ya! Don't take it too hard tho, you can always ask for help :D

**Comment by aniimessh** [comment]
![image](https://github.com/keyshade-xyz/keyshade/assets/97246133/442db64b-c4c1-416b-bf43-59d0db9e2b00)
Sir, why i am getting this error, sorry i am just a beginner

**Comment by rajdip-b** [comment]
No issues bro! I'll refer you some docs on how to get started. Follow that. If you still face the problem, LMK!

- This is just so that you know what all things you need: https://docs.keyshade.xyz/contributing-to-keyshade/prerequisites
- To get your environmental variables set up: https://docs.keyshade.xyz/contributing-to-keyshade/environment-variables
- How to develop the API: https://docs.keyshade.xyz/contributing-to-keyshade/running-things-locally/running-the-api

Also, just so you know, we are using pnpm for our project. So npm might not work!

**Comment by aniimessh** [comment]
Thanks You for your kind help

**Comment by rajdip-b** [comment]
> Thank You for your kind help

Sure! You can also hop on to our Discord server to have an indepth chat regarding this! Just letting you know.

**Comment by rajdip-b** [comment]
Hey bro @aniimessh! Could you make any progress on this?

**Comment by aniimessh** [comment]
Sorry sir,I won't be able to make any progess, I am just a begineer so I need more time  and currently my exams are approaching. Sorry

**Comment by rajdip-b** [comment]
Hey bro @aniimessh that's totally okay! Focus on your exam preparations. 

I'm making this issue up for grabs again. But do feel free to slide in when you feel like!

**Comment by DhairyaMajmudar** [comment]
Hi @rajdip-b I have done a quick vscode search to find the files to be changed for this issue. Below is the list for the same friend pls.  correct me if I am missing any file : )


```
1. api-key.service.ts
2. environment.service.ts
3. event.service.ts
4. integration.service.ts
5. prisma.repository.ts
6. project.service.ts
7. secret.service.ts
8. user.service.ts
9. variable.service.ts
10. workspace.service.ts
11. workspace-role.service.ts
```

**Comment by rajdip-b** [comment]
I don't think `prisma.repository.ts` would be included. Rest looks good.

**Comment by DhairyaMajmudar** [comment]
> I don't think `prisma.repository.ts` would be included. Rest looks good.

Cool, I'II not change that file, thanks for issue assignment =)

**Comment by rajdip-b** [comment]
Thanks to you for taking it up!
