### ISSUE TITLE
Remove supabase from docs

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#164]
## Description
Our docs still has the supabase requirements mentioned in it. We would like to remove that.

## Solution
You will need to update the `docs` folder in the repository to make the changes. These changes would be reflected in our GitBook docs.

These are the pages that needs to be changes:
- https://docs.keyshade.xyz/contributing-to-keyshade/prerequisites
- https://docs.keyshade.xyz/contributing-to-keyshade/environment-variables
- https://docs.keyshade.xyz/contributing-to-keyshade/design-of-our-code/api

**Comment by HarshPatel5940** [comment]
@prasanjit-4 wanna try?

**Comment by SRINJAYDASGUPTA-Git** [comment]
May i @rajdip-b ?

**Comment by rajdip-b** [comment]
Sure!

**Comment by SRINJAYDASGUPTA-Git** [comment]
@rajdip-b check out the pr

**Comment by rajdip-b** [comment]
In a min sir
