### ISSUE TITLE
Replace `nx` in docs with `turbo`

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#174]
## Description
[This](https://github.com/keyshade-xyz/keyshade/blob/develop/docs/contributing-to-keyshade/setting-things-up.md#installing-nx) file still contains info on getting NX configured, when in reality we have moved to Turbo. We need to update that.

## Solution
Add info on how to install turbo.

**Comment by voi-jankowski** [comment]
/attempt I'd like to work on this issue, if that's ok.
