### ISSUE TITLE
Create boilerplate for React SDK

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#18]
Genrate the boilerplate code for React SDK. The code should live inside `packages/sdk-react`. Use the `nx` CLI for doing this using the help of [this](https://nx.dev/nx-api/react) plugin.

**Comment by lakshay-saini-au8** [comment]
@rajdip-b I can take this one  and complete the whole flow for react sdk

**Comment by rajdip-b** [comment]
@lakshay-saini-au8 That's really great to hear man! Unfortunately, for creating the React SDK (implementation i mean), you will require the node-sdk which is still a WIP. So, for now, all you can do is, make the boilerplate, initialize the state (jotai or context API) preferred, and add some basic tests. We ofcourse will let you know once the node sdk is done! And many thanks for proposing to take up the entire flow!

I am assigning this issue, perhaps you can implement the things i mentioned!
