### ISSUE TITLE
Fix prisma-cli and prisma client version mismatch

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#184]
## Description

This is the error we are facing right now:
```
warn Versions of prisma@5.12.1 and @prisma/client@5.10.2 don't match.
This might lead to unexpected behavior.
Please make sure they have the same version.
```

## Solution

We want to upgrade `@prisma/client` to `5.12.1` or equivalent

**Comment by jamesfrye420** [comment]
Also removing Prisma as a dependency from [api](https://github.com/keyshade-xyz/keyshade/blob/3d5bcac76d5c5f64b13eb0f8e7bbd14a3101e322/apps/api/package.json#L40) as it is already a [top level dependency](https://github.com/keyshade-xyz/keyshade/blob/3d5bcac76d5c5f64b13eb0f8e7bbd14a3101e322/package.json#L131)

**Comment by jamesfrye420** [comment]
Why is Prisma Client a dev dependency? 

https://github.com/keyshade-xyz/keyshade/blob/3d5bcac76d5c5f64b13eb0f8e7bbd14a3101e322/package.json#L137

**Comment by rajdip-b** [comment]
> Why is Prisma Client a dev dependency?
> 
> https://github.com/keyshade-xyz/keyshade/blob/3d5bcac76d5c5f64b13eb0f8e7bbd14a3101e322/package.json#L137

The client package is for using it along `pnpx`. 

Also, what you can do is, move the top level prisma into the api since that's how we will need to make it work. If we need to fix some scripts for that (the ones prefixed with db:), then migrate them aswell!

**Comment by rajdip-b** [comment]
Okay!

**Comment by muntaxir4** [comment]
This is already fixed, now both `prisma` and `prisma/client` has equal versions 5.19.0. Reference: #209
