### ISSUE TITLE
Add docs for running the `web` locally

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#185]
## Description

Our docs don't include any information on how to run the `web` package locally. We would want to add that.

## Solution

You can refer the [running-the-api.md] file to start writing up this document. We would want this doc to include these steps in particular:
- Command to run the web package
- Command to test
- Where to view the web app from

**Comment by qhtutorials** [comment]
attempt/ I will add a contributing-to-keyshade/running-things-locally/running-the-web-package.md

**Comment by rajdip-b** [comment]
Sure!!!
