### ISSUE TITLE
Fix incorrect docs about testing the API

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#186]
## Description
![image](https://github.com/keyshade-xyz/keyshade/assets/83924254/2636c04e-b7de-4aac-9c88-e385b0d180fb)

This [portion](https://docs.keyshade.xyz/contributing-to-keyshade/running-things-locally/running-the-api#testing-your-code) of our docs is outdated. We need to update it with the latest testing steps.

## Solution
1. For the first command, unit tests of `api` are now performed using `pnpm run unit:api`
2. We have shifted to using `pnpm run e2e:api` for e2e tests
3. Remove the docker instructions. 
4. Lastly, we want to add another section, that includes both unit and e2e tests. We want to let the users know that they can skip the first two commands and run this directly, as this will perform the unit and e2e tests.

You will have to edit [this](https://github.com/keyshade-xyz/keyshade/blob/develop/docs/contributing-to-keyshade/running-things-locally/running-the-api.md) file to make the changes.

**Comment by veh3546** [comment]
Hi, I'd love to work on this but I have a clarifying question. What is the command for the new section instead of the 2 prior commands?

**Comment by rajdip-b** [comment]
Hey @veh3546, it was a grammatical mistake in my part. I have listed the two new commands in the first 2 lines of the description. Please feel free to do a /attempt to start working when you want to!

**Comment by veh3546** [comment]
/attempt https://github.com/keyshade-xyz/keyshade/pull/193

Is this what you had in mind?

**Comment by veh3546** [comment]
awaiting your review :)
