### ISSUE TITLE
API: Skip workspace creation if the user is an admin user

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#191]
## Description
Any user that gets created, gets a default workspace associated with them. We don't want admin accounts to get a default workspace. 

## Solution

- Add a `if` check in the [create-user.ts](https://github.com/keyshade-xyz/keyshade/blob/develop/apps/api/src/common/create-user.ts) file to skip creation of a workspace if the user is an admin user.
- Add relevant tests to `user.e2e.spec.ts` to check this case.

**Comment by DhairyaMajmudar** [comment]
/attempt

Taking this up : )
