### ISSUE TITLE
API: Set `strictNullChecks` to `true` in tsconfig.json

### ISSUE THREAD

**Issue by jamesfrye420** [keyshade-xyz/keyshade#198]
**Describe the bug**
Env variables when consumed is inferred to type `string`

**Expected behavior**
Env variables should be inferred to type `string | undefined` so that engineers are forced to handle edge cases with `undefined` for optional variables.

**Solution**
Set `strictNullChecks` to `true` in tsconfig.json.
Set `strict` to `true` in tsconfig.json

**Comment by rajdip-b** [comment]
I feel we should close it then!
