### ISSUE TITLE
Create React SDK

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#20]
Follow the same structure as #8

Depends on #18 #8

**Comment by Shu12388y** [comment]
@rajdip-b can you assign this issue to me

**Comment by rajdip-b** [comment]
> @rajdip-b can you assign this issue to me

Hey, currently we are not in a position to implement this feature. This heavily depends on 2 other issues, which are still in Todo. You would need to wait some time before we can actually make this :(
