### ISSUE TITLE
Husky Install command is deprecated

### ISSUE THREAD

**Issue by jamesfrye420** [keyshade-xyz/keyshade#201]
**Problem**
https://github.com/keyshade-xyz/keyshade/blob/3d5bcac76d5c5f64b13eb0f8e7bbd14a3101e322/package.json#L121

Husky Install Command is Deprecated

**Solution**

Update Husky according to the [changelog](https://github.com/typicode/husky/releases/tag/v9.0.1)

**Comment by Deepak-png981** [comment]
Hi , could you please assign this to me ?

**Comment by Deepak-png981** [comment]
Hi, I have raised a PR : https://github.com/keyshade-xyz/keyshade/pull/202 .
