### ISSUE TITLE
API: Cache user for optimized authentication

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#207]
## Description

keyshade uses stateless cookie-based authentication to let users in. In the long run, this will impose a strain on our database since we will have over 100qps. To optimize this, we would like to cache our user data during authentication.

## Solution

In [auth.guard.ts](https://github.com/keyshade-xyz/keyshade/blob/develop/apps/api/src/auth/guard/auth/auth.guard.ts#L55), if the authentication is successful, we fetch the user details and set it in the current session. We would also like to cache this data. We will be using the key structure `user-<userId>`.

- Import Redis in `auth.guard.ts`:
  ```ts
  @Inject(REDIS_CLIENT) readonly redisClient: {
      publisher: RedisClientType
  },
  ```
- Try to fetch the user from redis by the `user-<userId>`. If it's null, fetch from the database by email.
- `JSON.stringify()` the data retrieved, and set it in cache as `userId -> userObject(stringified)`
- In [user.serviec.ts](https://github.com/keyshade-xyz/keyshade/blob/develop/apps/api/src/user/service/user.service.ts#L29), whenever a user is updated, fetch the cached user, and update the value of the cache.

## Additional context

Relevant files can be found in `auth` and `user` module.

**Comment by z-xus** [comment]
/attempt I'd like to work on this issue for fosshack.

**Comment by Z-xus** [comment]
Hi, I need some help, I tried to create a user cache in the auth.guard.ts as you said, but while testing it only creates cache for the first user logged in (using Jwt token) and doesn't work further. I suspect that this may be related to the Guard not being called or some similar thing?

Here's what I have tried:
![image](https://github.com/user-attachments/assets/e8d49e39-19cd-42d2-8085-2791887efc2c)
It created hash for the first user but not for the second ( I logged the second one in after removing the cookie, too)
![image](https://github.com/user-attachments/assets/9ffa32a6-414f-4c56-8a22-b0fb6a5c6e2e)
My best guess is that I'm trying to cache in the wrong place..

**Comment by Z-xus** [comment]
My logic was to set cache only in auth module after successfully logging in because using cache there could sacrifice integrity of data

I was just setting a string so I'll try now with hashmap so it will be well segregated as well, hopefully that would work out.

Also, should I create a service for this caching? it seems to be used both times like setting after login and setting when user updates.

I appreciate your time and help.

**Comment by rajdip-b** [comment]
A cache service would be highly appreciated if you can make one. Maybe, you can create a separate module for that and export it globally. 

Also, as for your concerns regarding data integrity, those are valid. So in that case, at the very bottom of the function is a line that sets the user in the request body. You can implement the cache put operation just before that line.

**Comment by Z-xus** [comment]
When I try caching the user after successful login in the auth.service.ts it is working as expected. Should I go ahead with it? It seems that using otp and cookie, something about logging in auth guard is getting cached, I can't find out why
![image](https://github.com/user-attachments/assets/ed1cd709-1998-4a97-8c37-85c05f695232)
 
![image](https://github.com/user-attachments/assets/88159cf6-18f9-4deb-a158-51fdb85a6167)

**Comment by rajdip-b** [comment]
I think adding the cached user in this place works aswell. But then, the main use of cache is in the auth guard before we try to fetch the user from db. It wont make much sense if we just add the cache and not use it.

**Comment by Z-xus** [comment]
That's exactly the case I was referring to when I said data integrity, If a user{} cache is sent when trying to login a user, when an admin has deleted the user, then it would still allow the user to be logged in.. regardless of being deleted.

**Comment by Z-xus** [comment]
My approach was to set user in cache when they log in and then use the cached user for subsequent get requests made from user service/s.

**Comment by rajdip-b** [comment]
> when an admin has deleted the user, then it would still allow the user to be logged in.. regardless of being deleted.

For now, admin routes are disabled. And even if the admin deletes the user, we would also delete the user from the cache so it wont be an issue.

> My approach was to only set user in cache when they log in and then use the cached user for subsequent get requests made from user service/s.

As far as the scope of the issue is concerned with, we just want to use the cache in auth guard while authentication. Later on, we can add more such cache functions.
