### ISSUE TITLE
API: Change OTP code from alphanumeric to numeric

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#211]
## Description

Currently, the API sends an OTP while signing in or signing up with an email address. The problem isl, as per the standards, we should be sending a numeric OTP. But currently, it is alphanumeric. We would like to make this change.

## Solution

- Change the [OTP generation method](https://github.com/keyshade-xyz/keyshade/blob/develop/apps/api/src/auth/service/auth.service.ts#L47) to generate a 6-digit numeric code.

## Additional context

Make sure the tests pass. You won't need to add any other tests for this issue.

**Comment by lakshay-saini-au8** [comment]
@rajdip-b Please assign this issue

**Comment by rajdip-b** [comment]
Hey @lakshay-saini-au8, #230 fixes it, so I am removing your assignment.
