### ISSUE TITLE
API: `JWT_SECRET` not working properly.

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#214]
**Describe the bug**

We have migrated to using zod for validating our env schema (refer #200). Recently, I have encountered an error where we can't log in due to `JWT_SECRET` not being fetched properly. Rest assured, I have double-checked on the paths and environmental variables to ensure that everything else is working. 

Note that, if I try `console.log(process.env.JWT_SECRET)` anywhere else in the code, it outputs the expected value without fault. The error seems to be occurring in the `JwtModule` initialization in `auth.module.ts`. 

Also note, if I use `process.env.JWT_SECRET ?? 'some-value'` in the `JwtModule` registration code, it seems to work fine.
![image](https://github.com/keyshade-xyz/keyshade/assets/83924254/f0f13c35-3127-4bc1-979a-d0ff50b17abe)

**To Reproduce**
1. Run the API.
2. Use the `/api/auth/send-otp` endpoint to send an OTP to your email.
3. Copy the OTP and use `/api/auth/validate-otp` to validate your code. 
4. Encounter the `500 Internal Server Error` error in your response.

**Expected behavior**

- Authentication should have flowed smoothly.
- The user object should be reutrned as a response.
- The JWT bearer token should be sent as a cookie.

**Screenshots**

- Response error: 
![image](https://github.com/keyshade-xyz/keyshade/assets/83924254/86e13067-f9e2-423d-ba6f-b7b68cd40930)

- Console log
![image](https://github.com/keyshade-xyz/keyshade/assets/83924254/8fb930cc-d259-488c-9656-4af1f8ecded6)

**Additional context**

You can find the files in here:
- [zod validation files](https://github.com/keyshade-xyz/keyshade/tree/develop/apps/api/src/common/env)
- [JWT code](https://github.com/keyshade-xyz/keyshade/blob/develop/apps/api/src/auth/auth.module.ts#L15)

**Comment by jamesfrye420** [comment]
Can it be possibily because the `JWTModule` is trying to access env vars before they are read in the config module?

That would indicate that the JwtModule is being initialized before the config module is ready.

Could you verify this?

**Comment by rajdip-b** [comment]
The JWT code I linked belongs from the auth module. And in the top level app module, config module is initialised at the very beginning. So I'm doubtful if that might be the cause (I checked it the first thing).

**Comment by rajdip-b** [comment]
@jamesfrye420 could you link the PR? The solution you showed would work for now.

**Comment by jamesfrye420** [comment]
Sure, I just wanna check something before I push the pr. Will keep you updated

**Comment by shubham9069** [comment]
@rajdip-b Is this solved ? if it is still open so i can work on this

**Comment by rajdip-b** [comment]
Not really, but this isnt a priority at the moment.

**Comment by TAGISWILD** [comment]
This usually occurs when the environment loader fails to parse the secret or when the key is missing from the active runtime environment.

Double-check:
1. The `.env` file is present in the working directory from which the process is launched.
2. The key isn't wrapped in conflicting quotes or special characters that fail standard dotenv parsing.

To automatically verify that all necessary environment variables are set, correctly formatted, and meet security standards before runtime, you can integrate [dotvet](https://ethiccode.in/dotvet/):
```bash
npx dotvet
# or
pip install dotvet
```
It validates your environment setup in CI/pre-commit and halts execution if critical secrets like `JWT_SECRET` are missing or weak.
