### ISSUE TITLE
DOCS: Add documentation about our `web` package

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#219]
## Description

We would like to put up documentation about how our `web` package that is responsible for rendering our [homepage](https://keyshade.xyz).

## Solution

- Create a file named `web.md` in [`design-of-our-code`](https://github.com/keyshade-xyz/keyshade/tree/develop/docs/contributing-to-keyshade/design-of-our-code) folder.
- Refer to [`api.md`](https://github.com/keyshade-xyz/keyshade/blob/develop/docs/contributing-to-keyshade/design-of-our-code/api.md) to understand the structure of the documentation.
- Reference the new file in [this](https://github.com/keyshade-xyz/keyshade/blob/develop/docs/SUMMARY.md) and [this](https://github.com/keyshade-xyz/keyshade/blob/develop/docs/contributing-to-keyshade/design-of-our-code/README.md) files.

**Comment by vr-varad** [comment]
@rajdip-b I would like to work in this issue

**Comment by rajdip-b** [comment]
Sure! Go ahead.
