### ISSUE TITLE
Create the CLI

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#22]
## Description
The CLI lives under `apps/cli`. This package will be used to communicate with keyshade via the terminal. Users would be able to install this package via npm.

## Supported platforms
- Windows
- MacOS
- Linux (Debian, Fedora, Arch)

## Supported functionality
The CLI should be able to do the following:
- Log in a user using an API key
- Create projects
- Fetch projects
- Delete projects
- Update projects
- Create secrets
- Fetch secrets
- Delete secrets
- Update secrets
- Reveal secrets
- Add/Remove members from a project
- Update existing permissions of a user in a project
- Regenerate all secrets using a new private key
- Create API keys
- Update API keys
- Delete API keys (should not delete the key being used currently)
- Fetch API keys

**Comment by kriptonian1** [comment]
Assign to me ser

**Comment by rajdip-b** [comment]
Here you go ser!
