### ISSUE TITLE
API: Add logout endpoint 

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#223]
## Description

Add an endpoint to log out. The functionality will be very simple - just clear the `token` cookie.

## Solution

- Add a controller in auth controller.
- Do not add `@Public` to it.
- Create a service function that will unset the `token` cookie.

**Comment by rashmod** [comment]
@lakshay-saini-au8 Are you still working on this, or should I take it on?

**Comment by rajdip-b** [comment]
@rashmod you can get started with this one. It has been quite a long time since I've made the assignment

**Comment by rashmod** [comment]
The link for postman collection in docs in the API testing sections is broken 
@rajdip-b

**Comment by rashmod** [comment]
I'm looking to test the logout API endpoint, but I noticed that we don't have a traditional email and password login—just Google and GitHub OAuth. Would I need to run the frontend to test it, or am I missing something?
@rajdip-b

**Comment by rajdip-b** [comment]
We have email+OTP auth aswell. Whenever the login is successful, we are setting the jwt token in the cookie of the response. Further requests make use of this cookie when making a request.

You would need to implement a logic that will unset this cookie value.

**Comment by rashmod** [comment]
the precommit hook is failing because of the lining rules
but it is not failing for any of my changes but instead in app/web

**Comment by rajdip-b** [comment]
Yes, we are aware of this issue. The only way for us would be to disable the pro-commit hooks for now. 

But for your end, you can use --no-verify flag along with git commit to bypass hooks.

**Comment by ShreyamKundu** [comment]
@rajdip-b  I'm trying this and, as you mentioned, not adding @Public(). However, when I test the /api/auth/logout route, I’m getting this:
{
  "message": "Onboarding not finished",
  "error": "Unauthorized",
  "statusCode": 401
}

To avoid this, can I use BypassOnboarding?

**Comment by rajdip-b** [comment]
I don't think that should be done since users wont have the option to log out before their onboarding is finished.

**Comment by ShreyamKundu** [comment]
Any suggestions how to tackle this problem?

**Comment by rajdip-b** [comment]
That's a feature, not a problem. Once you authenticate yourself, you would need to use the "Update User" request in Bruno and set `isOnboardingFinished` flag to true. After that, all the operations would be unlocked.

**Comment by ShreyamKundu** [comment]
Okay I got it.
