### ISSUE TITLE
WEB: Add pricing page

### ISSUE THREAD

**Issue by kriptonian1** [keyshade-xyz/keyshade#227]
## Description
Implement the pricing page for keyshade website. The pricing page should be on route `/pricing`.

## Figma file

https://www.figma.com/design/agXphjCREPVedcay4cQtLP/Keyshade-Home?m=dev&node-id=1%3A1665&t=jBDazGdj8IE5kkaY-1

## Design

[![Pricing](https://github.com/keyshade-xyz/keyshade/assets/74916308/99c95329-c57e-4fc8-bcd6-69807d61f0f5)](https://www.figma.com/design/agXphjCREPVedcay4cQtLP/Keyshade-Home?m=dev&node-id=1%3A1665&t=jBDazGdj8IE5kkaY-1)

**Comment by HarshPatel5940** [comment]
> @HarshPatel5940 would you be able to take this up / refer someone?

I would try to do this or ask if one of my friends are interested

**Comment by rajdip-b** [comment]
Cool!

**Comment by kriptonian1** [comment]
any updates??
