### ISSUE TITLE
API: Add emoji icon and total projects in a workspace

### ISSUE THREAD

**Issue by kriptonian1** [keyshade-xyz/keyshade#229]
## Description
We need to have emoji as an icon for workspace and total number of project a workspace have for aesthetic purpose of the ui. 
Also, remove the `description` field.

## Screenshot

<img width="307" alt="image" src="https://github.com/keyshade-xyz/keyshade/assets/74916308/d8854afd-88e2-47a2-8899-65f439739d15">

**Comment by Princeyadav05** [comment]
@rajdip-b if possible, can I work on this next?

**Comment by rajdip-b** [comment]
Totally! We would be glad! Also, you can refer to [this](https://github.com/keyshade-xyz/keyshade/blob/develop/CONTRIBUTING.md#self-assigning-issues) to understand how you can self assign issues

**Comment by rajdip-b** [comment]
@kriptonian1 can you please tell us in what format we are supposed to store the emoji?

**Comment by kriptonian1** [comment]
ig we need to store it in unicode.

https://towardsdatascience.com/emojis-in-your-data-9a5513ead2dd

**Comment by rajdip-b** [comment]
Looks perfect.

**Comment by rajdip-b** [comment]
@Princeyadav05 hey bro, have you started with this one yet?

**Comment by Princeyadav05** [comment]
> @Princeyadav05 hey bro, have you started with this one yet?

Hi bro, no have not started. Didn't get a chance in the last 2 days, was planning to do it on the weekend.

**Comment by rajdip-b** [comment]
Sure thing! Just that this is on priority so I checked in on you. Do let us know when you get started :)

**Comment by Princeyadav05** [comment]
@rajdip-b I was able to run the project locally, can see the platform on localhost:3025. However, its stucked on auth page. I'm not able to signup or use any authentication.

**Comment by Princeyadav05** [comment]
@rajdip-b can you share the discord invite? The one in the readme is invalid.

**Comment by rajdip-b** [comment]
Here you go! https://discord.com/invite/T8eg8FHB

**Comment by kriptonian1** [comment]
> @rajdip-b I was able to run the project locally, can see the platform on localhost:3025. However, its stucked on auth page. I'm not able to signup or use any authentication.

have you tried running both the server together

**Comment by jamesfrye420** [comment]
https://github.com/twitter/twemoji


This might be helpful. Check this out @rajdip-b 

All you would need for emojis.

**Comment by rajdip-b** [comment]
@kriptonian1 thoughts?

**Comment by kriptonian1** [comment]
I don't find it that that useful, rather what we can do is take the emoji and reder it in a png like they do in whatsapp. gonna make that in rust would be easy code

**Comment by singhankit62000** [comment]
/attempt I'd like to work on this issue

**Comment by kriptonian1** [comment]
@singhankit62000 how is it going ?
