### ISSUE TITLE
API: Get the email to send feedbacks to from `process.env`

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#235]
## Description

https://github.com/keyshade-xyz/keyshade/blob/5ea9a10d1972cf6865faa0c051ed9de595eb6d47/apps/api/src/feedback/service/feedback.service.ts#L17

It would be a good practice to keep things dynamic so that the code can be easily configured without making any code changes. We would like to parse the email, where we want to send the feedbacks sent by the users, from `process.env`.

## Solution

- Create an environmental variable named `FEEDBACK_FORWARD_EMAIL`
- Add it in `.env.example`
- Add it in zod schema

**Comment by Princeyadav05** [comment]
Hi @rajdip-b , Can i try this issue? Seems a pretty easy one.
I'm confident I would be able to solve this.

**Comment by rajdip-b** [comment]
Sure thing dude! Here you go

**Comment by Princeyadav05** [comment]
@rajdip-b have created a PR with the fix. LMK if anything needs to be changed.

**Comment by rajdip-b** [comment]
Awesome! I'll review it whenever I'm free again.
