### ISSUE TITLE
PLATFORM: Add create new project

### ISSUE THREAD

**Issue by kriptonian1** [keyshade-xyz/keyshade#244]
## Description

Implement a “create new project” functionality in the dashboard of the platform. The created new project should be immediately updated in the project dashboard. Some part of create new project is done, which can find in [`apps/platform/src/app/(main)/page.tsx`](https://github.com/keyshade-xyz/keyshade/blob/develop/apps/platform/src/app/(main)/page.tsx). 

## Scope of work

You have to implement 2 features from create new project. 
1. Add environment for the project, by default there is an environment named `default`. In the array of object environment, there should be only one default workspace. And user can add as many environments as they want.
2. After sending the environment request. The project dashboard should auto refresh to show the recently added project.

### Postman URL
- [Create project](https://www.postman.com/blue-crescent-581920/workspace/keyshade/api/a31bdb66-69e3-469b-afb4-f2051385e634/request/32733901-299c8b25-c346-4610-b3a2-dd043728da3c?collection=32733901-fae1f431-06fa-4425-aef4-65b28e9e9e71&version=63ff7d1a-5155-4cf3-ae4f-75c552aef059)

### Type of new project and environment

https://github.com/keyshade-xyz/keyshade/blob/f3a36326b4f5c945fb2725620ff92ab31e44e053/apps/platform/src/types/index.ts#L43-L54

### Dialog for create new project

https://github.com/keyshade-xyz/keyshade/blob/f3a36326b4f5c945fb2725620ff92ab31e44e053/apps/platform/src/app/(main)/page.tsx#L116-L187

**Comment by ayan-joshi** [comment]
@kriptonian1 @rajdip-b I would like to work on this issue can u assign me under FOSS HACK

**Comment by rajdip-b** [comment]
Sure!

**Comment by kriptonian1** [comment]
@ayan-joshi best of luck buddy, let me know if you need any help

**Comment by ayan-joshi** [comment]
@kriptonian1 there is postman url attached which is not opening will I need it for my work ?

[Create project](https://www.postman.com/blue-crescent-581920/workspace/keyshade/api/a31bdb66-69e3-469b-afb4-f2051385e634/request/32733901-299c8b25-c346-4610-b3a2-dd043728da3c?collection=32733901-fae1f431-06fa-4425-aef4-65b28e9e9e71&version=63ff7d1a-5155-4cf3-ae4f-75c552aef059)

**Comment by rajdip-b** [comment]
> @kriptonian1 there is postman url attached which is not opening will I need it for my work ?
> 
> [Create project](https://www.postman.com/blue-crescent-581920/workspace/keyshade/api/a31bdb66-69e3-469b-afb4-f2051385e634/request/32733901-299c8b25-c346-4610-b3a2-dd043728da3c?collection=32733901-fae1f431-06fa-4425-aef4-65b28e9e9e71&version=63ff7d1a-5155-4cf3-ae4f-75c552aef059)

Yeap! Here's the updated link: https://www.postman.com/keyshade/workspace/keyshade

**Comment by ayan-joshi** [comment]
@rajdip-b I have a question , for this pr I would need to setup all 4 ports and can u help me with project setting up

**Comment by rajdip-b** [comment]
Hey @ayan-joshi! You can refer to our docs to understand how to set things up: https://docs.keyshade.xyz/contributing-to-keyshade/summary

**Comment by ayan-joshi** [comment]
@rajdip-b I got it running locally , how to pass through auth page can u help?

**Comment by rajdip-b** [comment]
You would need to sign up like usual. Make sure the API is running.

**Comment by kriptonian1** [comment]
Hey @ayan-joshi, you need to run the API server and the platform simultaneously, and you need to create a `.env` file inside the platform and there add `NEXT_PUBLIC_BACKEND_URL=http://localhost:4200`

**Comment by ayan-joshi** [comment]
> NEXT_PUBLIC_BACKEND_URL=http://localhost:4200

@kriptonian1 Yes I have done it already , I have got docker running , api is running too but I cant go past the auth page

**Comment by kriptonian1** [comment]
Can you show the errors in console

**Comment by ayan-joshi** [comment]
> Can you show the errors in console

![image](https://github.com/user-attachments/assets/74968bc6-2961-4407-8601-c0af99c903ac)

**Comment by kriptonian1** [comment]
> > Can you show the errors in console
> 
> ![image](https://private-user-images.githubusercontent.com/96243602/352034811-74968bc6-2961-4407-8601-c0af99c903ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTc5NzksIm5iZiI6MTcyMTg5NzY3OSwicGF0aCI6Ii85NjI0MzYwMi8zNTIwMzQ4MTEtNzQ5NjhiYzYtMjk2MS00NDA3LTg2MDEtYzBhZjk5YzkwM2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA4NTQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZmQ5OWI3N2VhMGUyMzMxMjFiMDA0ZGY0NDI4OWQzOWQyN2VmYjdiOGJhYjEwY2M4ODU3MTY4YTY0ZjNlMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-ck8Jcoz48JjyEHL178MP8kGxv24g5HyZK19eZWEwFc)

Are you running the api in parallel ?

**Comment by ayan-joshi** [comment]
> > > Can you show the errors in console
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/96243602/352034811-74968bc6-2961-4407-8601-c0af99c903ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTc5NzksIm5iZiI6MTcyMTg5NzY3OSwicGF0aCI6Ii85NjI0MzYwMi8zNTIwMzQ4MTEtNzQ5NjhiYzYtMjk2MS00NDA3LTg2MDEtYzBhZjk5YzkwM2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA4NTQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZmQ5OWI3N2VhMGUyMzMxMjFiMDA0ZGY0NDI4OWQzOWQyN2VmYjdiOGJhYjEwY2M4ODU3MTY4YTY0ZjNlMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-ck8Jcoz48JjyEHL178MP8kGxv24g5HyZK19eZWEwFc)
> 
> Are you running the api in parallel ?

yes

**Comment by kriptonian1** [comment]
If you are free then maybe we can get on a call tomorrow

**Comment by rajdip-b** [comment]
This is related to error in your SMTP creds if im not wrong. I would advise you to call the endpoint from postman once

> > Can you show the errors in console
> 
> ![image](https://private-user-images.githubusercontent.com/96243602/352034811-74968bc6-2961-4407-8601-c0af99c903ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MjMzNDYsIm5iZiI6MTcyMTkyMzA0NiwicGF0aCI6Ii85NjI0MzYwMi8zNTIwMzQ4MTEtNzQ5NjhiYzYtMjk2MS00NDA3LTg2MDEtYzBhZjk5YzkwM2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDE1NTcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlOTQxZmIzODg3NzEzMGQyODYwMzZlNzdkNjczMTJmMDIyMTk0NDlmMDU0NDQyZjQyOWM0ZmNkZTY5MGNkM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p33L0mQyaNVYbh3LNXghGUbxmfod_n_X5DoIC5gCPWM)

**Comment by rajdip-b** [comment]
@ayan-joshi unassigning due to inactivity
