### ISSUE TITLE
WEB: Fix encrypt text glitch in footer

### ISSUE THREAD

**Issue by kriptonian1** [keyshade-xyz/keyshade#249]
## Describe the bug
When you hover on footer texts which have a larger width than the section heading, then the text animation is glitching.
## To Reproduce
Steps to reproduce the behaviour:
1. Scroll down to footer
2. Hover on `Terms and Conditions` or `Secret Scanner`
3. you will see the text to be glitching.

## Expected behaviour
It is expected to behave like the other texts whose width is not bigger than the heading of the section.

## Screenshots

https://github.com/keyshade-xyz/keyshade/assets/74916308/dc48e190-c52c-4f4c-8d26-c4d88b039216

## Files to look into
- [encrypt-text.tsx](https://github.com/keyshade-xyz/keyshade/blob/665ff96a5157e4d497eb5ced7367db7a3705d95b/apps/web/src/components/ui/encrypt-text.tsx)

**Comment by Aleesssino** [comment]
/attempt I would like to work on this!

**Comment by kriptonian1** [comment]
Hey @Aleesssino sure man, go ahead. Let me know if you need any help.
