### ISSUE TITLE
Add docker build and run commands to `package.json`

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#257]
## Description

Adding the docker commands to `package.json` will help developers to better test their builds. 

## Solution

Add the following scripts to the root `package.json`:

- `docker:build:api`
- `docker:run:api`
- `docker:build:web`
- `docker:run:web`
- `docker:build:platform`
- `docker:run:platform`

**Comment by vr-varad** [comment]
@rajdip-b for clarification what would be the web-image name?

**Comment by rajdip-b** [comment]
Okay so you can use this pattern: 

- ks-web
- ks-platform
- ks-api

**Comment by vr-varad** [comment]
the platform doesn't have a docker file @rajdip-b

**Comment by rajdip-b** [comment]
Ah shoot, would you mind adding one? Ideally, you would just need to copy and paste the `web` Dockerfile and modify it. 

@kriptonian1 I don't think we need to do anything else?

P.S. @vr-varad it is okay if you would just like to put up a pr for web and api. We can open another issue for platform.
