### ISSUE TITLE
PLATFORM: Add `Dockerfile` to `platform`

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#259]
## Description

We would like to containerize the [`platform`](https://github.com/keyshade-xyz/keyshade/tree/develop/apps/platform) package. Add a dockerfile to this package.

## Solution

- Add a Dockerfile in `/apps/package`. You can refer to [this](https://github.com/keyshade-xyz/keyshade/tree/develop/apps/platform)
- Add two scripts in root `package.json`: `docker:build:platform` and `docker:run:platform`. Refer to #258

**Comment by DhairyaMajmudar** [comment]
Hi, @rajdip-b this seems to be an interesting issue to solve can you pls. mind assigning me. In past I have exp. of dockerising JSON Schema Org. website which is built on the similar tech stack  keyshade is built on 
Thank you : )

**Comment by rajdip-b** [comment]
We would be glad to @DhairyaMajmudar! All the best!

**Comment by DhairyaMajmudar** [comment]
> We would be glad to @DhairyaMajmudar! All the best!

Thanks will give my best

**Comment by DhairyaMajmudar** [comment]
Also @rajdip-b can you pls. also add this issue in the FossHack issue board.

**Comment by rajdip-b** [comment]
Sure thing boss!

**Comment by DhairyaMajmudar** [comment]
Thanks, man, you are awsm =)

**Comment by DhairyaMajmudar** [comment]
@rajdip-b the docker file is ready but I am facing a lot of build failures due to type-checks, Shall I incorporate the changes in the same PR or open a new issue?

![image](https://github.com/keyshade-xyz/keyshade/assets/124715224/d65b5d96-141e-4ede-83f5-42fec724cee0)

**Comment by rajdip-b** [comment]
I would say, if it's avoidable, then just let it be like this for now. We can always iterate over this. But if this PR requires this type check to pass, then you can put up the implementation in the same PR. Totally depends upon how you want it to be done!

**Comment by DhairyaMajmudar** [comment]
Removing my assignment since this issue is resolved.
