### ISSUE TITLE
API: Update return type while fetching secrets and variables

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#261]
## Description

We would like to cluster the response of fetching secrets and variables by the environment they belong to. For example: 

- `/api/secrets/all/:projectId`
  ```json
  [
    {
      "environmentName": "dev",
      "environmentId": "dev-1234",
      "secrets": []
    },
    {
      "environmentName": "prod",
      "environmentId": "prod-1234",
      "secrets": []
    }
  ]
  ```

- `/api/variables/all/:projectId`
  ```json
  [
    {
      "environmentName": "dev",
      "environmentId": "dev-1234",
      "variables": []
    },
    {
      "environmentName": "prod",
      "environmentId": "prod-1234",
      "variables": []
    }
  ]
  ```

## Solution

- Update [`SecretService#getAllSecretsOfProject`](https://github.com/keyshade-xyz/keyshade/blob/develop/apps/api/src/secret/service/secret.service.ts#L424)
- Update [`VariableService#getAllVariablesOfProject`](https://github.com/keyshade-xyz/keyshade/blob/develop/apps/api/src/variable/service/variable.service.ts#L408)

**Comment by Ritika1705** [comment]
Hi, is your website or backend down by any chance?

**Comment by Ritika1705** [comment]
@rajdip-b 

![image](https://github.com/keyshade-xyz/keyshade/assets/54587414/4851549f-490c-41cd-ac5c-691c831806f9)
![image](https://github.com/keyshade-xyz/keyshade/assets/54587414/8bee903e-94bb-4631-90eb-685790093169)

**Comment by rajdip-b** [comment]
Hey @Ritika1705! Thanks for pointing out. We are actively dealing with this issue to set up redirection.

When we initiated, out servers were located at https://keyshade.xyz. Now, it is located at https://www.keyshade.xyz/. Although the redirection should take place automatically, you would need to tell your browser atleast once that the new address exists.

**Comment by Ritika1705** [comment]
Thankyou @rajdip-b, but while testing the API : {{BASE_URL}}/api/auth/send-otp/:email?= in Postman, I still get internal serve r error. Can you help me?

**Comment by rajdip-b** [comment]
> Thankyou @rajdip-b, but while testing the API : {{BASE_URL}}/api/auth/send-otp/:email?= in Postman, I still get internal serve r error. Can you help me?

Are you sure you have passed in the email? If yes, could you check the logs from the server?

P.S. could you please join our Discord do discuss the issue? We prefer using that! https://discord.com/invite/JpWY7Gjd

**Comment by Ritika1705** [comment]
Ok sure

**Comment by rajdip-b** [comment]
@jamesfrye420 if you are attempting this, could you please mark you attempt?
