### ISSUE TITLE
Update GitHub Action plugin versions

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#262]
## Description

Most of the current plugins are outdated, we would like to update them. You can find all the workflow files in `.github/workflows`

## Solution

Listing all the plugins with the latest version. Search the files by the plugin name and update to the version specified in here.

- aws-actions/configure-aws-credentials@v4
- actions/checkout@v4
- aws-actions/amazon-ecr-login@v2
- amannn/action-semantic-pull-request@v5

**Comment by anudeeps352** [comment]
/attempt I'd like to work on this issue.
