### ISSUE TITLE
API: Replace for loop with array indexing while decrypting secrets during bulk fetch

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#265]
## Description

When we fetch secrets by a project ID, we only include the latest version of the secret. Currently, while decrypting the value, we are unnecessarily running a while loop. We would like to replace this with just `const version = secret.versions[0]`

https://github.com/keyshade-xyz/keyshade/blob/020bbf642335fb98db59e83ec722f24490f36d03/apps/api/src/secret/service/secret.service.ts#L496

![image](https://github.com/keyshade-xyz/keyshade/assets/83924254/15c01819-5494-47de-b0d9-e702d0be42ca)

**Comment by anudeeps352** [comment]
/attempt I'd like to work on this issue.
