### ISSUE TITLE
DOCS: Add a separate page under "Running things locally" and name it "Docker support"

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#279]
## Description

Our `package.json` file includes commands on how to build and run the packages using Docker. We would like to have a docs page dedicated to that.

## Solution

- Create a page named **Docker support**. Name the slug `docker-support`
- Add instructions on how to build and run each of the app under `apps/` directory
- Refer to `package.json` to get the commands

**Comment by YuvalBubnovsky** [comment]
/attempt

let's get it
