### ISSUE TITLE
Create Dockerfile for API

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#29]
Create a Dockerfile for the API under `apps/api`. Make sure that you properly use the `ENV` directive to list all the environmental variables the API is using. You can find them from both the code and the `.env.example`

**Comment by ezhil56x** [comment]
@rajdip-b Can I get this assigned?

**Comment by rajdip-b** [comment]
Absolutely man we will be much pleased. Do follow the Dockerdile-web convention and name the new file Dockerdile-api. I will review the PR at the earliest

**Comment by rajdip-b** [comment]
hey @ezhil56x, could you make any progress on this one?

**Comment by ezhil56x** [comment]
On it. Will raise a PR next week

**Comment by rajdip-b** [comment]
great!
