### ISSUE TITLE
CLI: Add path resolution

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#290]
## Description

Right now, the imports in the CLI app is using relative paths. We would like to change that to use `@` prefixed path. 

## Solution

Map the following paths in the `tsconfig.json` file and update the usage:
- `src/util` → `@util`
- `src/http` → `@http`
- `src/commands` → `@commands`

**Comment by DhairyaMajmudar** [comment]
Issue completed in this PR https://github.com/keyshade-xyz/keyshade/pull/334

**Comment by rajdip-b** [comment]
I think yes!
