### ISSUE TITLE
CLI: Create a function to validate the fields

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#291]
## Description

Our CLI blindly trusts the user input. We would like to put some validation in the following places:
- In the options of `configure` command
- In case options are not provided, then in the terminal input of `configure` command
- The parsed data from the config files when using `run` command

## Solution
- Create a `validate.ts` file under `util` directory. 
- Add a class name Validate
- Add a method with the following function prototype: `static configurationParameters(data: ProjectRootConfig & UserRootConfig)`
- In here, based on the type of fields in the interfaces, validate them properly
- If validation fails, throw an appropriate error

We would like to use zod for this.

**Comment by rajdip-b** [comment]
Hey @shubham9069! Sure thing, you can take this up! 

Also, there are a lot of unattempted API issues that you might want to take a look at: https://github.com/keyshade-xyz/keyshade/issues?q=is%3Aissue+is%3Aopen+label%3A%22scope%3A+api%22+no%3Aassignee

Do let me know if you would like to take this up, or if you would like to take a dig at the API issues first.

**Comment by shubham9069** [comment]
@rajdip-b  okay we can tackle a Issue first then jump into a development

**Comment by rajdip-b** [comment]
Sure!

**Comment by shubham9069** [comment]
@rajdip-b here is my profile https://shubhamkaushik-portfolio.vercel.app/ please look into it and assign a task based on a prior basis I wanna help you out, guys

**Comment by shubham9069** [comment]
@rajdip-b give me list of task where i can work on it

**Comment by rajdip-b** [comment]
Your profile looks real good! 

- If you are here to attempt Foss Hack issues, there are a few unattempted issues left out that you can try: https://github.com/keyshade-xyz/keyshade/issues?q=is:issue+is:open+label:%22foss+hack%22+no:assignee
- If you want to help us out in our urgent development issues, these are a few that you can get started with: https://github.com/keyshade-xyz/keyshade/issues?q=is:issue+is:open+no:assignee+label:%22scope:+cli%22

Just comment /attempt on any issue to self assign it and get started!

**Comment by shubham9069** [comment]
@rajdip-b okay got it

**Comment by rajdip-b** [comment]
You can also hop on to our Discord channel to discuss about the issues: https://discord.gg/dh8F3Dzt

**Comment by Princeyadav05** [comment]
@rajdip-b not sure if there is a UserRootConfig interface in the code.

**Comment by rajdip-b** [comment]
Hey @Princeyadav05! Thanks for pointing this out. This issue has got outdated and I need to update this with the latest details. That being said, the scope of the issue is still valid
