### ISSUE TITLE
CLI: Add pnpm commands to run the CLI

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#293]
## Description

We need to add the commands for the following things:

- **TypeScript watch build:** `apps/cli/package.json` has a `watch` script. We would like to add another script named `dev:cli` in the root `package.json` file to delegate the call
- **Running the index.js build:**: Add a script `start:cli` in root package.json that will be able to execute `node apps/cli/dist/index.js`. Note that we would also want this script to work with the parameters. Below is the current and expected usage:
  ```bash
  node apps/cli/dist/index.js configure --workspace <>
  ```
  ```bash
  pnpm start:cli -- --workspace <>
  ```

**Comment by Mihan786Chistie** [comment]
Hey @rajdip-b I would like to try solving this issue

**Comment by rajdip-b** [comment]
Sure! Go ahead.

**Comment by rajdip-b** [comment]
> Sure! Go ahead.

Refer to #289 to understand how it works.

**Comment by rajdip-b** [comment]
@Mihan786Chistie hey, one more thing. This issue is related to FOSS Hack. So if you are not registered with them, you can do that right away: https://fossunited.org/fosshack/2024

If you would like to attempt without wanting to register to FOSS Hack, I can remove the `foss hack` label.

**Comment by Mihan786Chistie** [comment]
@rajdip-b I'm registered to Foss Hack

**Comment by rajdip-b** [comment]
Awesome!
