### ISSUE TITLE
WEB: Modify deployment rules

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#296]
## Description
https://github.com/keyshade-xyz/keyshade/blob/68f51a5121bb28496b06984438be0bbacc6b60a6/.github/workflows/deploy-web.yml#L4

Modify the pipeline to run only if any files under `apps/web` or root `package.json` changes.

**Comment by DhairyaMajmudar** [comment]
Hi @rajdip-b It seems like the paths are added in workflow https://github.com/keyshade-xyz/keyshade/blob/develop/.github/workflows/deploy-web.yml#L8

Anything else needed to be done in this issue ?

**Comment by rajdip-b** [comment]
Ah boy, this is really challenging to keep up with the changes! Thanks a lot for pointing this out.
