### ISSUE TITLE
CLI: Convert objects in `http` folder to classes

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#299]
## Description

The following files contains objects of the controller call implementation. We would like to convert the objects to classes and make the functions static:

- https://github.com/keyshade-xyz/keyshade/blob/cb0f3011b37f238a2470480ee9e978eaf56702cf/apps/cli/src/http/auth.ts#L4
- https://github.com/keyshade-xyz/keyshade/blob/cb0f3011b37f238a2470480ee9e978eaf56702cf/apps/cli/src/http/secret.ts#L3
- https://github.com/keyshade-xyz/keyshade/blob/cb0f3011b37f238a2470480ee9e978eaf56702cf/apps/cli/src/http/variable.ts#L3

**Comment by vr-varad** [comment]
@rajdip-b I would like to work upon this issue!!

**Comment by rajdip-b** [comment]
Feel free to do so! But first, do make sure you are have registered with FOSS hack. You can refer to this discussion: https://github.com/keyshade-xyz/keyshade/discussions/284

**Comment by vr-varad** [comment]
@rajdip-b I have made a pr.
