### ISSUE TITLE
[USER] Log in using GitHub

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#3]
Users should be able to log in to our platform using GitHub. When doing so, we should scrape off the following things and persist them in our db: 
- avatar
- name
- email

**Comment by Abbhiishek** [comment]
Hey @rajdip-b,

I can work on this and #4 at the same time. Assign me ser

**Comment by rajdip-b** [comment]
Okei ser here you go!

**Comment by Abbhiishek** [comment]
Hey @rajdip-b @kriptonian1 can you guys suggest some styling and base color for login and signup routes ?

<img width="714" alt="image" src="https://github.com/keyshade-xyz/keyshade/assets/86338762/50ec872b-b131-4aa7-975b-40749462f842">

This is default with PrimaryColor as Black

The below is another option is another option 

<img width="458" alt="image" src="https://github.com/keyshade-xyz/keyshade/assets/86338762/9fae2831-9f66-4be5-9a69-f29dbf7a92ec">


Let me know what looks good to both of you 😊

**Comment by Abbhiishek** [comment]
Also how can i access the Prisma client to do Operations ?

**Comment by rajdip-b** [comment]
> Also how can i access the Prisma client to do Operations ?

You solely need to figure out this one ig. Maybe you can use some webhooks Or something. I'm entirely unsure about how clerk does it

**Comment by rajdip-b** [comment]
> Hey @rajdip-b @kriptonian1 can you guys suggest some styling and base color for login and signup routes ?
> 
> <img alt="image" width="714" src="https://private-user-images.githubusercontent.com/86338762/293488960-50ec872b-b131-4aa7-975b-40749462f842.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5OTc2OTUsIm5iZiI6MTcwMzk5NzM5NSwicGF0aCI6Ii84NjMzODc2Mi8yOTM0ODg5NjAtNTBlYzg3MmItYjEzMS00YWE3LTk3NWItNDA3NDk0NjJmODQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA0MzYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4YmU3M2FlOGU2MmNlYjQyOWM0YjJjYWZiZGM1MjNjMjBhN2NjNTZjMjkwMTI2YjZkMTc1ODRmMTQzY2NlMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C1ceejLNAyk3ktOtl3Al5iuaN4dqW50Oo4xQDoT6kic">
> This is default with PrimaryColor as Black
> 
> The below is another option
> 
> <img alt="image" width="458" src="https://private-user-images.githubusercontent.com/86338762/293488991-9fae2831-9f66-4be5-9a69-f29dbf7a92ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5OTc2OTUsIm5iZiI6MTcwMzk5NzM5NSwicGF0aCI6Ii84NjMzODc2Mi8yOTM0ODg5OTEtOWZhZTI4MzEtOWY2Ni00YmU1LTlhNjktZjI5ZGJmN2E5MmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA0MzYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZjBmMmNlZjliNTg2ODdiNWYyMDI4Y2M3MTVhNTk3ZTkxMmUwYzQzZDQ3YWFiYzNlNDllMDJlYzhmZGY4NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0S9Q1Y2gcGNlH2xsJU5LoAofWjyR0WELQWEb8KWtB1M">
> Let me know what looks good to both of you 😊

Confirming this shortly

**Comment by HarshPatel5940** [comment]
Attempting to work on this using `passport` as discussed in https://github.com/keyshade-xyz/keyshade/pull/49#issuecomment-1873902182

**Comment by rajdip-b** [comment]
Sure, go ahead!

**Comment by rajdip-b** [comment]
@HarshPatel5940 for now, just focus on the backend implementation

**Comment by HarshPatel5940** [comment]
> @HarshPatel5940 for now, just focus on the backend implementation

Noted.
