### ISSUE TITLE
CLI: Add functionality to operate on Environments

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#300]
## Description

We would like to perform the following operations for project using our CLI:

- List all environments under a project (`keyshade environment list <projectId>`)
- Get a particular environment by id (`keyshade environment get <environmentId>`)
- Create an environment (`keyshade environment create <projectId> (refer postman for parameters)`)
- Edit an environment (`keyshade environment update <environmentId> (refer postman for parameters)`)
- Delete an environment (`keyshade environment delete <environmentId>`)

## Solution

- Create an implementation of `command.interface.ts` and name if `EnvironmentCommand`.
- Stash all the functions in `src/commands/environment`.
- Add environment specific API functionality in `src/http/project.ts` and name the class EnvironmentController.

**Comment by vr-varad** [comment]
@rajdip-b As my last preview is approved I would like to work on this issue.

**Comment by rajdip-b** [comment]
Hey! Sure. But could you hold up for a day or two? We are making some changes in how the configuration works. After that we will be sharing the how-to guide for developing the CLI.

**Comment by vr-varad** [comment]
yeah Sure.

**Comment by rajdip-b** [comment]
@vr-varad Hey bro! Could you make any progress on this yet?

**Comment by vr-varad** [comment]
Yeah Actually I was waiting for ur reply @rajdip-b Should I make a pr now?

**Comment by rajdip-b** [comment]
Oh, yeah absolutely! You can make it now. This isn't related to foss hack so won't be an issue.
