### ISSUE TITLE
CLI: Add functionality to operate on Variables

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#301]
## Description

We would like to perform the following operations for variable using our CLI:

- List all variables under a project (`keyshade variable list <projectId>`)
- Fetch all revisions of a variable (`keyshade variable revisions <variableId>`)
- Create a variable (`keyshade variable create <projectId>(refer postman for parameters)`)
- Update a variable (`keyshade variable update <variableId> (refer postman for parameters)`)
- Rollback a variable (`keyshade variable rollback <variableId> --environment-slug/-e <> --version/-v <>`)
- Delete a variable (`keyshade variable delete <variableId>`)

## Solution

- Create an implementation of `command.interface.ts` and name if `VariableCommand`.
- Stash all the functions in `src/commands/variable`.
- Use the `variableController` from `ControllerInstance` to make the API calls.

**Comment by anudeeps352** [comment]
Btw I thought I'd take this up since I'm already doing the secrets thing on CLI.Kinda similiar right.So it would be easier ig

**Comment by rajdip-b** [comment]
SGTM

**Comment by anudeeps352** [comment]
@rajdip-b I've linked the pr. Do check it out when you're available
