### ISSUE TITLE
API: Implement global search feature in workspace

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#309]
## Description

Given a certain workspace, we would like to search the following items by partial name or note/description:
- projects
- environments
- secrets
- variables

Also note, we would only like to display the items that the user has access to.

## Solution

- Create an endpoint in `workspace.controller.ts` with the path `/:workspaceId/global-search/:searchTerm`
- The `searchTerm` would be a non-null string field
- Fetch `projects`, `environments`, `secrets`, `variables` whose name resemble with the search term.
- Return the response in the following format:
  ```typescript
  {
    projects: {
      id: string,
      name: string,
      description: string
    } [],
    environments: {
      id: string,
      name: string,
      description: string
    } [],
    variables: {
      id: string,
      name: string,
      note: string
    } [],
    secrets: {
      id: string,
      name: string,
      note: string
    } []
  }
  ```

**Comment by rajdip-b** [comment]
@kriptonian1 looks good?

**Comment by kriptonian1** [comment]
Yeap

**Comment by Tirthchoksi22** [comment]
@rajdip-b  Hey I am participating Foss Hack so should i made the PR right now or during the hackathon ??

**Comment by rajdip-b** [comment]
Hey buddy! We already have a few PRs related to the hackathon. As per the guidelines, the hackathon hours are the best for it. But if you want to, you can also make the PR now. 

But, we won't be able to merge them before the timeline!

**Comment by Tirthchoksi22** [comment]
@rajdip-b Hey I have made the PR pls review it

**Comment by Tirthchoksi22** [comment]
@rajdip-b Volunteer of the foss hacks are saying that the PR commits at the time of hackathons will only be considered for evaluation so what should I do now as I have made the commit already

**Comment by rajdip-b** [comment]
You can take down the PR! No worries about that. Alternatively, you can also ask them about what can be done. 

If they are looking at the commit timeline, I would say you can redo this entire commit once again in the hackathon window.

**Comment by rajdip-b** [comment]
@Tirthchoksi22 could you please join our Discord channel aswell? We have quite a few active FOSS contributors over there, so we can discuss this problem :)

**Comment by Tirthchoksi22** [comment]
> You can take down the PR! No worries about that. Alternatively, you can also ask them about what can be done. 
> 
> If they are looking at the commit timeline, I would say you can redo this entire commit once again in the hackathon window.

Yess they are looking at the commit timeline so better I take down the PR but before that pls review it tell me the change so at the hackathon time I can just directly commit with the changes

**Comment by rajdip-b** [comment]
> > You can take down the PR! No worries about that. Alternatively, you can also ask them about what can be done.
> > If they are looking at the commit timeline, I would say you can redo this entire commit once again in the hackathon window.
> 
> @rajdip-b they are looking at the commit timeline so better I take down the PR but before that pls review it tell me the change so at the hackathon time I can just directly commit with the changes

Yeap! That's underway :)

**Comment by rajdip-b** [comment]
Okay look, about the PR:

- I feel that you shouldn't tie up the existing service classes together because that will introduce coupling, and also there are many redundant database calls included.
- A single method named `globalSearch` under the workspace service would be enough imo. Then, you can use prisma to query for everything. 

If you go through our permission structure, you would find that there is an `AuthorityChecker` class that does all the heavylifting of RBAC. So in this case, you would need to do the following:

- In the controller endpoint, you would need to set the following authorities: `READ_WORKSPACE`, `READ_PROJECT`, `READ_ENVIRONMENT`, `READ_SECRET` and `READ_VARIABLE`
- In the service layer, query all the projects. Then, for each project, use this function to query the allowed authorities: https://github.com/keyshade-xyz/keyshade/blob/e238e9582f63c6bf7fee7364d2a0e7e128fd03a9/apps/api/src/common/get-collective-project-authorities.ts#L13
- Once that done, for every `project -> authorities[]` entry, check if for a project, `READ_WORKSPACE`, `READ_PROJECT`, `READ_ENVIRONMENT`, `READ_SECRET` and `READ_VARIABLE` exist in its allowed authorities. If yes, keep the project, if no, remove the project from this entry list.
- Then, query all the projects, environments, secrets and variables whose name and/or description/note matches the search query. Include a where block for every entity on the `project` field to only select entities if the `project.id` is `in some` of the previously calculated project list.

**Comment by Tirthchoksi22** [comment]
so i dont have to write seperate methods in project service but for this i have to make indiviual methods like 'getprojects' in workspace.service itself and same with the other three. will it be fine than?

**Comment by rajdip-b** [comment]
> so i dont have to write seperate methods in project service but for this i have to make indiviual methods like `getprojects` in workspace.service itself and same with the other three. will it be fine than?

Yeap that would be correct.
