### ISSUE TITLE
Update `auto-assign.yml` to change the status of associated project of issue

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#316]
## Description

Whenever someone uses `/attempt` on any issue, the GitHub action pipeline in `auto-assign.yml` assigns the commenter the issue. If the issue has any project associated with it, we would like to change its current status to "In Progress". An issue might have 0 to n number of projects assigned to it, we would like `auto-assign.yml` to be updated in a way to change the status of all these projects.

**Comment by DhairyaMajmudar** [comment]
Let's do it 🚀

/attempt
