### ISSUE TITLE
CLI: Add linting support and validation workflow

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#317]
## Description

Add linting support for our `cli` package.  Also, we would like to run validation when a PR is opened.

## Solution

- Add `lint:cli` in `package.json`
- Add a `validate-cli.yml` file that will validate the CLI package whenever a PR is opened or changes are pushed. Refer to `validate-web.yml`. For now, we would only like to run `pnpm lint:cli` in that pipeline.

**Comment by DhairyaMajmudar** [comment]
On it 

/attempt
