### ISSUE TITLE
PLATFORM: Add skeleton loader in secret

### ISSUE THREAD

**Issue by kriptonian1** [keyshade-xyz/keyshade#322]
## Description 

Add a skeleton loader in secret page for the time the data is loading from the server.

---
this issue is dependent on the merge of PR #313

**Comment by rajdip-b** [comment]
@Nirajan1-droid Moving this to FOSS Hack. Hope you are comfortable with that?

**Comment by Nirajan1-droid** [comment]
absolutely

**Comment by rajdip-b** [comment]
Great! Okay, #313 is merged. You can begin your work.

**Comment by Nirajan1-droid** [comment]
would you please help me to resolve this error:
after deploying the migrations the schemas are not listed in db:
![image](https://github.com/keyshade-xyz/keyshade/assets/65585311/3699e22b-fde6-4b05-97cb-58b3d318472c)
also there  is "Error while checking if bucket exists in Minio"

![image](https://github.com/keyshade-xyz/keyshade/assets/65585311/b1526073-dc4d-4ef4-92fc-f9394e9aeb8c)

**Comment by kriptonian1** [comment]
Buddy it looks like you are not reading the setup doc, if you do then you won't have all these issues

**Comment by Nirajan1-droid** [comment]
i followed docs>contributing-to-keyshade>setting-things-up.md
:'|

**Comment by rajdip-b** [comment]
Howdy @Nirajan1-droid!

There is an issue with name resolution since prisma is including the quotes in the names while creating the schemas, so its a bit tricky at first to check them out. Ideally, they should reside like this -> `public."SchemaName"`(including the quotes)

As for the Minio error in the console, you can ignore that since we are not yet using buckets.

Hope that solves it!

**Comment by Nirajan1-droid** [comment]
Would you please send me the video to set it up correctly? I have wasted hours and hours on it, and still, the Postgres database does not have any tables in it.

**Comment by rajdip-b** [comment]
Hey @Nirajan1-droid, you would have to use the following commands once you have connected to the database: 

- Show all the databases using `\l` ![image](https://github.com/user-attachments/assets/e1cda01e-1776-40a8-bfc7-a35f705d26ba)
- Set `keyshade_db`in the context using `\c keyshade_db` 
![image](https://github.com/user-attachments/assets/e8dadecd-c011-41b4-9f5e-a264541346fd)
- Now you can list all the relations using `\dt`
![image](https://github.com/user-attachments/assets/60e7356f-45df-42f6-a4be-cbe2e519150e)

Hope these steps help. Do let us know if you run into any further trouble.

**Comment by Nirajan1-droid** [comment]
@rajdip-b @kriptonian1 i am still facing this migration related issue.


is api working correctly as "Error while checking if bucket exists in Minio"?:
![image](https://github.com/user-attachments/assets/7f321fdc-83d2-40a9-b6e0-361f2aa20361)

but even after the migration being pusehd, there are no relations in the docker postgres container:
![image](https://github.com/user-attachments/assets/0e139825-15b1-4817-8cea-98d03a928bab)

i checked it serveral times.
also the api server cannot be connected :
![image](https://github.com/user-attachments/assets/54d2186d-f6cf-47c8-886d-541afb449266)

this was the .env file:
DATABASE_URL=postgresql://postgres:password@127.0.0.1:5432/keyshade_db
ADMIN_EMAIL=your@email.com

REDIS_URL=redis://127.0.0.1:6379

GITHUB_CLIENT_ID= 
GITHUB_CLIENT_SECRET= 
GITHUB_CALLBACK_URL=

API_PORT= 

GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_CALLBACK_URL=

GITLAB_CLIENT_ID=
GITLAB_CLIENT_SECRET=
GITLAB_CALLBACK_URL=

SENTRY_DSN=
SENTRY_ORG=
SENTRY_PROJECT=
SENTRY_TRACES_SAMPLE_RATE=
SENTRY_PROFILES_SAMPLE_RATE=
SENTRY_ENV=

SMTP_HOST=
SMTP_PORT=
SMTP_EMAIL_ADDRESS=nirajanolass@gmail.com
SMTP_PASSWORD=5@Shifts
FROM_EMAIL="your-name <your-name@email.com>"

MINIO_ENDPOINT='localhost'
MINIO_PORT=9000
MINIO_ACCESS_KEY=<my_access_key>
MINIO_SECRET_KEY=<my_secret_key>
MINIO_USE_SSL=false
MINIO_BUCKET_NAME=<my_bucket_name>

JWT_SECRET=secret

WEB_FRONTEND_URL=http://localhost:3000
PLATFORM_FRONTEND_URL=http://localhost:3100
PLATFORM_OAUTH_SUCCESS_REDIRECT_PATH=/oauth/signin
PLATFORM_OAUTH_FAILURE_REDIRECT_PATH=/oauth/failure

DOMAIN=localhost
FEEDBACK_FORWARD_EMAIL=nirajanbhattarai12345@gmail.com

BACKEND_URL=http://localhost:4200


containers are working well:
![image](https://github.com/user-attachments/assets/c28525c7-9686-41dd-8ca4-64ad3d6e745d)

ps: you can unassign me this issue if it is hectic and time consuming for you guys. i don't want to waste your time.

**Comment by rajdip-b** [comment]
1. You can remove all the Minio configs from your .env file since they are optional. Try again and the error should have resolved.
2. The issue with postgres is really difficult to debug. I would say, turn off the docker container using `docker compose down`. Then, run `pnpm db:deploy-migrations`. This should throw an error stating that it couldn't connect to the database. If that is not the case, then there is some other postgres database running on your device.

P.S. This issue isn't on the top priorities, so you can take your time in this.

**Comment by Nirajan1-droid** [comment]
@rajdip-b 
i got help from one brother and fixed that postgres error.
now that migration worked.
but why it is requesting port 3200 while login?
![image](https://github.com/user-attachments/assets/6dcbbdad-fc53-4d8b-b98e-d3871fd462be)

**Comment by rajdip-b** [comment]
Yeah, this one is a shortcoming from our end. Just add `NEXT_PUBLIC_BACKEND_URL=http://localhost:4200` to your `.env` file

**Comment by Nirajan1-droid** [comment]
yes i did same:
![image](https://github.com/user-attachments/assets/3ee2760f-60bb-47e3-a6ac-cfb5f3c7fa45)
but i am having 401 unauthorized code.
although the backend is running correctly:
![image](https://github.com/user-attachments/assets/e621f8ad-55be-4019-94d9-71b1222785a2)
also database have that email:
![image](https://github.com/user-attachments/assets/d19a295d-77b0-47a6-881e-816e8759aa19)

**Comment by Nirajan1-droid** [comment]
i resolved that login error and otp issues.
now when i want to add project, i am having this error:
![image](https://github.com/user-attachments/assets/f35a08a4-c9cd-43ef-9975-378d21678762)

what is this error?

**Comment by kriptonian1** [comment]
Ignore that that feature is not complete

**Comment by rajdip-b** [comment]
> @rajdip-b i resolved that login error and otp issues. now when i want to add project, i am having this error: ![image](https://private-user-images.githubusercontent.com/65585311/349251599-f35a08a4-c9cd-43ef-9975-378d21678762.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTI5MDYsIm5iZiI6MTcyMTE5MjYwNiwicGF0aCI6Ii82NTU4NTMxMS8zNDkyNTE1OTktZjM1YTA4YTQtYzljZC00M2VmLTk5NzUtMzc4ZDIxNjc4NzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA1MDMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZTEyYTY0MmZlZDcwYzQ0OTcwY2ZkYzljNTFmMGFiODAzYzUxZDRiOGY5ZjczYjM0NjRhNDQzZTllNjY5OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.68HZ7Vh-d0p-pHdNropyks2qkfcJlYVG-gbS3ixYCe8)
> 
> what is this error?

I'm unaware about the progress of the platform app. If you are facing some difficulties in creating a project from the UI, you can use the postman collection aswell.

**Comment by Nirajan1-droid** [comment]
postman link doesnot works which was provided in docs:
![image](https://github.com/user-attachments/assets/a60c41b1-7983-4a96-ab3d-04d05cfceb45)

**Comment by rajdip-b** [comment]
https://www.postman.com/keyshade/workspace/keyshade/api/a31bdb66-69e3-469b-afb4-f2051385e634?action=share&creator=32733901

Can you try this?

**Comment by PriyobrotoKar** [comment]
@kriptonian1 I can try this issue, but in the closed PR I saw that you said to implement the loading UI with react suspense. But as all the components and pages are client-side, the suspense will not work ig.

**Comment by kriptonian1** [comment]
@PriyobrotoKar  Yes you are right I totally forgot about that, you can go ahead and make it without suspense then
