### ISSUE TITLE
Resend OTP feature

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#325]
## Description

![image](https://github.com/keyshade-xyz/keyshade/assets/83924254/37acb5d9-32bb-40a8-b454-8c6fc7cbafb6)

We need to come up with an implementation to resend the OTP to the users. The resend functionality should have a timeout of 1 minute.

## Solution

- [ ] Add an API implementation to support resending OTP. (#326)
- [ ] Update the UI to feature resending OTP. (#327)

**General Note:** This is a join issue, so this ticket will be considered as completed only if both the issues are marked as complete.
**Note for FOSS Hack**: We saw a few requests for team collaboration. We feel that this would be the best place to do so!

**Comment by harshdeshmukh21** [comment]
I would like to contribute to this project. I feel I can do this task according to the need. I have registered my team via Foss Hack.

**Comment by rajdip-b** [comment]
Hey @harshdeshmukh21! Thanks for showing interest in this issue, but unfortunately this is already assigned. If you still want to contribute to this, I would recommend you to have a chat with the assigned members in the sub issues.

Alternatively, your team can pick up any of the other issues.

**Comment by Prakhargarg-2010196** [comment]
@rajdip-b  I am taking this entire thing hope so it wouldn't be an issue will be back in few days with some solution?

**Comment by rajdip-b** [comment]
Yeap thats fine!

**Comment by Prakhargarg-2010196** [comment]
Why do we use params for sending data to `api/send-otp/:email` and not POST body?

**Comment by rajdip-b** [comment]
There's no reason to be very honest. We could have used request body, but we didn't. 

- Is it anti-pattern? Yes. 
- Is it causing a lot of trouble? No. 
- Is it exposing sensitive data? No (i believe)

**Comment by Prakhargarg-2010196** [comment]
> There's no reason to be very honest. We could have used request body, but we didn't.
> 
> * Is it anti-pattern? Yes.
> * Is it causing a lot of trouble? No.
> * Is it exposing sensitive data? No (i believe)

Okay @rajdip-b I am following the same in resend otp, one thing more when do i have to run migrations in prisma like I am trying to utilise the existing logic of the sendOtp service by calling it in the resendOtp function but its showing some prisma issues..

**Comment by rajdip-b** [comment]
Until and unless you modify `schema.prisma`, you don't need to run migrations. But when you do, you need to run `pnpm db:generate-migrations`.

Whether you run migrations or not, you would need to run `pnpm db:generate-types` so that typescript can infer the types.

And lastly, you would be deploying the migrations using `pnpm db:deploy-migrations` in the following cases:
- You have set up the code for the first time
- You have taken a pull that contains new migrations
- You have generated a migration by yourself.

**Comment by Prakhargarg-2010196** [comment]
This can be closed i guess now @rajdip-b

**Comment by rajdip-b** [comment]
Could you please link the pr here? I think we missed it

**Comment by Prakhargarg-2010196** [comment]
> Could you please link the pr here? I think we missed it
> 

The related issues of this PR are solved @rajdip-b can check.

**Comment by rajdip-b** [comment]
Yes, I'm asking for that PR link. Because i think it was not linked to the issue. I'll link it and close the issue

**Comment by Prakhargarg-2010196** [comment]
> Yes, I'm asking for that PR link. Because i think it was not linked to the issue. I'll link it and close the issue

I don't think so the combined PR exists but the  Related PR are 
#445 and #489

**Comment by rajdip-b** [comment]
Fixed by
- https://github.com/keyshade-xyz/keyshade/pull/445
- https://github.com/keyshade-xyz/keyshade/pull/489
