### ISSUE TITLE
API: Resend OTP endpoint

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#326]
## Description

Add an implementation to support resending OTP to the user.

## Solution

- Add an endpoint `resend-otp/:email` in `auth.controller.ts`
- Add a service level implementation of the same in `auth.service.ts`
- Ideally, we want to rate limit this to ensure users don't get to call this endpoint in a short interval. We would like to impose a timeout of 1 minute per email address to invoke this endpoint. Refer to [this](https://docs.nestjs.com/security/rate-limiting)
- Note that, we just want to check if the user by the exists in the database. If yes, we want to resend the OTP.

**Comment by RockingThor** [comment]
Will love to work on this issue. Can I get this assigned to me, please?

**Comment by rajdip-b** [comment]
Sure @RockingThor!

Please read through our [documentation](https://docs.keyshade.xyz) and our contribution guidelines and feel free to get started :D

**Comment by Prakhargarg-2010196** [comment]
Did the api for this got implemented or is it yet to be done ? @rajdip-b

**Comment by rajdip-b** [comment]
I don't think so. It's still up for grabs.

**Comment by Prakhargarg-2010196** [comment]
Okay One more thing can you guide me a little how to setup that smtp thing mentioned in the mail ?
