### ISSUE TITLE
PLATFORM: Show warning sonner toaster if OTP is invalid

### ISSUE THREAD

**Issue by kriptonian1** [keyshade-xyz/keyshade#332]
## Description

In the current auth flow, there is no visual indicator for the user to know that the entered OTP is invalid. Therefore, we want to implement [`sonner`](https://ui.shadcn.com/docs/components/sonner)'s [Rich color warning](https://arc.net/l/quote/enrwcmur) state to prompt the user that the entered OTP is incorrect.

## Scope of Work
- Implement the [Rich color warning](https://arc.net/l/quote/enrwcmur) of [`sonner`](https://ui.shadcn.com/docs/components/sonner) in the `/auth/otp` page, if `/api/auth/validate-otp` is returning `401 Unauthorised`
- After you get the `401 Unauthorised` from the backend, set the `isLoading` state to false, so that the user can send the correct OTP next time

you can find the file to `/auth/otp` in `apps/platform/src/app/auth/otp/page.tsx`

**Comment by PriyobrotoKar** [comment]
@kriptonian1 what message the toast banner should display? Something like "Invalid OTP"?

**Comment by kriptonian1** [comment]
Maybe it could be “The OTP you entered is not valid, Please enter the right OTP”
This is what came to my mind, you can change it if you have something better

**Comment by PriyobrotoKar** [comment]
Got it 👍 
Also, I saw a small issue in this same otp form where the whole page was getting refreshed if otp input field is empty and then it was redirected back to the Getting Started page.
This can be easily fixed with e.preventDefault(). Do you think I should add this?
