### ISSUE TITLE
API: Add pagination metadata

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#336]
## Description

Add the following fields when returning paginated response in every module:
- `page`: The current page number
- `perPage`: The number of items per page
- `pageCount`: The total page count
- `totalCount`: The total number of items present
- `links` (All links to have the relative path. For example: `/api/environment/all/:projectId?<query>`)
  - `self`: The link to this current page
  - `first`: The link to the first page
  - `previous`: The link to the previous page
  - `next`: The link to the next page
  - `last` : The link to the last page

We want the computation to be done in the service classes.

## Solution

- Create a utility function under `common` module and name it `paginate`. This function should take in the page details and generate the pagination metadata
- Update all the functions in the service layer that return paginated data to return the data in `items` and the metadata in `metadata`
- Update the E2E test of the module to reflect on the changes

## Objectives

This issue is the parent issue. Below you will find a list of issues that relate to this. These issues encompass the scope of change in every module:

- #345
- #337
- #338
- #339
- #340
- #341
- #342
- #343
- #344

**Comment by muntaxir4** [comment]
This will cause the return type of affected methods to be Objects such that to hold those required fields right? And currently these methods return Arrays of Objects. The new result would be like `{ data : [...], ...fields}`

**Comment by rajdip-b** [comment]
Exactly!

**Comment by muntaxir4** [comment]
Can you assign me the whole list of issues? As of now I have implemented locally for the Project module.

**Comment by rajdip-b** [comment]
Hey @muntaxir4! Yeah, I think I can do that. Just note that, you would need to make the commits and put up the PR in the hackathon window :)
