### ISSUE TITLE
API: Add pagination metadata to Environment module

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#337]
## Description

Refer to #336 

## Scope of change
- https://github.com/keyshade-xyz/keyshade/blob/bc15eadf33a4ddc8ed496decd16e979aaf71ada9/apps/api/src/environment/service/environment.service.ts#L158-L203

**Comment by ATHARVA-JADHAV** [comment]
I'd like to work on this issue. This will be my first time contributing code to an open-source project, Could you please offer some guidance or share any helpful information to get me started?

**Comment by rajdip-b** [comment]
Hey @ATHARVA-JADHAV! The parent issue is already assigned to someone! Could you please look around for some other issues? I can assign them to you.

**Comment by muntaxir4** [comment]
/attempt Already working on its parent issue #336
