### ISSUE TITLE
API: Add pagination metadata to Project module

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#338]
## Description

Refer to #336 

## Scope of change

- https://github.com/keyshade-xyz/keyshade/blob/bc15eadf33a4ddc8ed496decd16e979aaf71ada9/apps/api/src/project/service/project.service.ts#L577-L609
- https://github.com/keyshade-xyz/keyshade/blob/bc15eadf33a4ddc8ed496decd16e979aaf71ada9/apps/api/src/project/service/project.service.ts#L625-L672

**Comment by muntaxir4** [comment]
/attempt I am assigned to its parent issue #336
