### ISSUE TITLE
API: Add pagination metadata to Workspace module

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#339]
## Description

Refer to #336 

## Scope of change

- https://github.com/keyshade-xyz/keyshade/blob/bc15eadf33a4ddc8ed496decd16e979aaf71ada9/apps/api/src/workspace/service/workspace.service.ts#L452-L517
- https://github.com/keyshade-xyz/keyshade/blob/bc15eadf33a4ddc8ed496decd16e979aaf71ada9/apps/api/src/workspace/service/workspace.service.ts#L723-L757

**Comment by anjali2004arya** [comment]
Hey, I am Anjali. I am one of the participants of FOSS Hack. I would like to contribute to this issue.

**Comment by rajdip-b** [comment]
Hey @anjali2004arya! The parent issue is unfortunately already assigned :( Could you please look around the other issues? and see if you can pick anything else up?

**Comment by anjali2004arya** [comment]
sure @rajdip-b

**Comment by muntaxir4** [comment]
/attempt Already working on the parent issue
