### ISSUE TITLE
API: Add pagination metadata to Workspace Role module

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#340]
## Description

Refer to #336 

## Scope of change

- https://github.com/keyshade-xyz/keyshade/blob/bc15eadf33a4ddc8ed496decd16e979aaf71ada9/apps/api/src/workspace-role/service/workspace-role.service.ts#L298-L328

**Comment by muntaxir4** [comment]
/attempt Already working in the parent issue.
