### ISSUE TITLE
API: Add pagination metadata to Secret module

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#341]
## Description

Refer to #336 

## Scope of change

- https://github.com/keyshade-xyz/keyshade/blob/bc15eadf33a4ddc8ed496decd16e979aaf71ada9/apps/api/src/secret/service/secret.service.ts#L495-L619

**Comment by muntaxir4** [comment]
/attempt I am attempting it's parent issue #336
