### ISSUE TITLE
API: Add pagination metadata to Variable module

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#342]
## Description

Refer to #336 

## Scope of change

- https://github.com/keyshade-xyz/keyshade/blob/bc15eadf33a4ddc8ed496decd16e979aaf71ada9/apps/api/src/variable/service/variable.service.ts#L490-L605

**Comment by muntaxir4** [comment]
/attempt i am assigned the parent issue #336
