### ISSUE TITLE
API: Add pagination metadata to Integration module

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#343]
## Description

Refer to #336 

## Scope of change

- https://github.com/keyshade-xyz/keyshade/blob/bc15eadf33a4ddc8ed496decd16e979aaf71ada9/apps/api/src/integration/service/integration.service.ts#L227-L306

**Comment by muntaxir4** [comment]
/attempt i am assigned the parent issue #336
