### ISSUE TITLE
API: Add pagination metadata to Event module

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#344]
## Description

Refer to #336 

## Scope of change

- https://github.com/keyshade-xyz/keyshade/blob/bc15eadf33a4ddc8ed496decd16e979aaf71ada9/apps/api/src/event/service/event.service.ts#L13-L58

**Comment by MelloB1989** [comment]
Hey I am Kartik Deshmukh. I am one of the participants in the FOSS Hack. We want to contribute to this issue and I feel confident my contribution will help!
/attempt

**Comment by rajdip-b** [comment]
@MelloB1989 Hello! I saw you have commented on quite a few issues. Would you please comment /attempt on each one of them so that you can be self assigned?

**Comment by muntaxir4** [comment]
/attempt I am attempting its parent issue #336
