### ISSUE TITLE
API-CLIENT: Create controllers to make request on behalf of the client apps

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#347]
## Description

The [`api-client`](https://github.com/keyshade-xyz/keyshade/tree/develop/packages/api-client) package contains a set of controllers to make calls to the API. We would use these controllers from the CLI and the platform to perform all the API related operations. As a result, we would like to have all the client requests in this `api-client` package.

Currently, we just have the controller for `Environment` module, but we would like to add all the other ones aswell. Here's the list:

- Workspace
- User
- Project
- Variable
- Secret
- Integration
- User
- Workspace Role
- Workspace Membership
- Event

## Solution

This is a parent issue, and all other issues linked to this would follow the same pattern. Just that the scope of implementation will vary. Here are the general pointers that should be implemented:

- Create a `controller` under [`src/controllers`](https://github.com/keyshade-xyz/keyshade/tree/develop/packages/api-client/src/controllers/) and name it as `<module-name>.ts`.
- Implement all the API calls from within this controller. Refer to [this](https://github.com/keyshade-xyz/keyshade/blob/develop/packages/api-client/src/controllers/environment/environment.ts)
- Add the request and response types under `src/types/<module-name>.types.d.ts`. Refer to [this](https://github.com/keyshade-xyz/keyshade/blob/develop/packages/api-client/src/types/environment.types.d.ts)
- Add relevant tests under `tests/<module-name>.spec.ts`. Refer to [this](https://github.com/keyshade-xyz/keyshade/blob/develop/packages/api-client/tests/environment.spec.ts) 

## Objectives

- #348
- #349
- #350
- #351
- #352
- #353
- #354
- #355
- #356
- #446

**Comment by surya-moorthy** [comment]
so adding api-controller makes  a structured code and easier read

**Comment by NangunooriAbhinav** [comment]
Hey, my name is Abhinav. I am one of the participants of FOSS Hack. We would like to to contribute to this issue.

**Comment by rajdip-b** [comment]
Hey @NangunooriAbhinav! We would love that! Could you please comment /attempt on any of the sub issue(s)? 

P.S. We would love to assign all of these to you but then there might be others who might also want to attempt them.

**Comment by NangunooriAbhinav** [comment]
Yea sure, i will make sure to leave a comment on a sub issue.

Me and my team will be looking forward to contributing to these issues.

**Comment by rajdip-b** [comment]
That would be awesome!
