### ISSUE TITLE
API-CLIENT: Create controller for Workspace module

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#348]
## Description 

Refer to #347 

API Controller: https://github.com/keyshade-xyz/keyshade/blob/develop/apps/api/src/workspace/controller/workspace.controller.ts

**Comment by NangunooriAbhinav** [comment]
Hey, my name is Abhinav. I am one of the participants of FOSS Hack. We would like to to contribute to this issue.

**Comment by rajdip-b** [comment]
Sure!

**Comment by rajdip-b** [comment]
@NangunooriAbhinav any progress on this?

**Comment by vr-varad** [comment]
@rajdip-b Would like to work on this

**Comment by rajdip-b** [comment]
> @rajdip-b Would like to work on this

Hey man, that would be really great. Although, I would need you to hold up for some time since I'm doing some housekeeping of the packages. Once it's done, you would be good to go :)

**Comment by vr-varad** [comment]
@rajdip-b just let me know when u are done!!

**Comment by rajdip-b** [comment]
Surely! You can track #362. Merging this will mean that we're clear.

Also, we are trying to create another package called `@keyshade/inputs` to validate the input types from both the `platform` and `cli`. So, I believe all the tests would be again impacted. But anyways, I feel you can continue.

**Comment by rajdip-b** [comment]
Done! You can start now.

**Comment by rajdip-b** [comment]
@vr-varad hey bro, are you on it?

**Comment by vr-varad** [comment]
hey @rajdip-b ya just some just the tests are remaining will be done by today! was stuck so couldn't complete

**Comment by rajdip-b** [comment]
Awesome!

**Comment by rajdip-b** [comment]
> hey @rajdip-b ya just some just the tests are remaining will be done by today! was stuck so couldn't complete

Hey bro :( I unfortunately didn't notice that you were assigned and I have come up with the solution myself
