### ISSUE TITLE
API-CLIENT: Create controller for Workspace Role module

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#355]
## Description 

Refer to #347 

API Controller: https://github.com/keyshade-xyz/keyshade/blob/develop/apps/api/src/workspace-role/controller/workspace-role.controller.ts

**Comment by surya-moorthy** [comment]
hi i would like to work on this issue

**Comment by surya-moorthy** [comment]
and contribute to this project

**Comment by rajdip-b** [comment]
Sure! Would love to have you work on this issue. Do hit us up on discord or in here in case you need some help. And don't forget to read the docs!

**Comment by surya-moorthy** [comment]
if i can able to work on this issue can i able to work on other api controller issue that you have assigned

**Comment by surya-moorthy** [comment]
share your discord link,please..

**Comment by rajdip-b** [comment]
https://discord.com/invite/E6s2BuAx

Here you go!
