### ISSUE TITLE
API: Add `prod` environment

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#357]
## Description

Add a `prod` environment support in API's zod schema parser. We want to move out the Sentry stuff from `devEnvironment` to `prodEnvironment` 

https://github.com/keyshade-xyz/keyshade/blob/1756727849a2bfabf9d58a81e95d7b6f6c159f4a/apps/api/src/common/env/env.schema.ts#L50-L55

**Comment by jamesfrye420** [comment]
how exactly would the validation change?

**Comment by rajdip-b** [comment]
We want to remove the sentry stuff from dev environment into prod environment, and also add a `NODE_ENV=prod` type

**Comment by jamesfrye420** [comment]
Cool I'll look into it within this week

**Comment by rajdip-b** [comment]
@manasveer6 any progress?
