### ISSUE TITLE
Create workflow for lint

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#36]
## Description
It would be nice to have a GitHub Action workflow file that will use the `pnpm run lint` and `pnpm run test` (individually) upon the following events:
- Pull Request submitted
- Push made to any branch

## Tasks
- [ ] API (#38)
- [ ] CLI (#39)
- [ ] SDK Node (#40)

**Comment by Abbhiishek** [comment]
Assign me sir

**Comment by rajdip-b** [comment]
P.S. @Abbhiishek assigned you the Login issues!

**Comment by HarshPatel5940** [comment]
hello @rajdip-b, can you assign me #39 and #40 would like to work on that as well.

also let me know if a single PR is fine to close both those issues

**Comment by rajdip-b** [comment]
Yes! It's totally possible to do that. Make refs to all three issues and we can do it in 1 pr.

**Comment by HarshPatel5940** [comment]
> Yes! It's totally possible to do that. Make refs to all three issues and we can do it in 1 pr.

Noted.

**Comment by HarshPatel5940** [comment]
@rajdip-b we can close this issue! As its completed by #46

**Comment by rajdip-b** [comment]
Yes absolutely!
