### ISSUE TITLE
CLI: Parse `profile create` input using zod

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#361]
## Description

https://github.com/keyshade-xyz/keyshade/blob/4bd12f0b7b1f0dc601cf661cdae3ba27c1d45354/apps/cli/src/commands/profile/create.profile.ts#L70-L93

After we have taken the input from the users, we would like to validate the data using zod.

### Validation types

- `name`: String containing the charset a-z,A-Z,0-9, and no spaces
- `baseUrl`: If not empty, then should be a valid URL
- `apiKey`: Should start with `ks_` and have characters in a-z,A-Z,0-9
- `setDefault`: If specified, should be either true or false.

**Comment by sujal-sakpal** [comment]
Hi , 
I’d like to take on the task of integrating input validation with Zod. I’ll define validation schemas for each input field, use zod to ensure the data meets our criteria, and then integrate this into our parseInput function. 
Could you please assign this to me?

**Comment by rajdip-b** [comment]
Sure thing @sujal-sakpal! All the best. 

Do not hesitate to ping us in here or in over Discord in case you run into any issues :D
