### ISSUE TITLE
API: Include default workspace of user in `getSelf` function 

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#365]
## Description

When we call `GET /api/user/`, we are responded with the details of the user. We would also like to include the details of the default workspace of the user. 

## Solution

The update would be scoped to this block: https://github.com/keyshade-xyz/keyshade/blob/581629dfc8917f86d008044e22e806af4abd20db/apps/api/src/user/service/user.service.ts#L34-L36

- Add a field called `defaultWorkspace` and include the details in there.
- Update the tests accordingly to reflect this change in `user.e2e.spec.ts`

**Comment by rajdip-b** [comment]
@anjali2004arya any progress on this?

**Comment by rajdip-b** [comment]
Removed assignment because of inactivity. Please feel free to pick it up in case you want to.

**Comment by unamdev0** [comment]
@rajdip-b can you please clarify how to find which workspace is the default workspace of a user? In case user is added to just one workspace we can return that, but in case user is part of multiple workspaces, how do we decide which one is the default one?

**Comment by rajdip-b** [comment]
Hi! By default, when a user is created, a default workspace gets created for them. Every workspace has a `isDefault` and `ownerId` field. So in your case, you would need to find the workspace that has isDefaul= true and ownerId = user ID. Hope that makes sense.

**Comment by unamdev0** [comment]
Oh ok, got it thanks!!
