### ISSUE TITLE
GENERAL: Only allow PNPM

### ISSUE THREAD

**Issue by kriptonian1** [keyshade-xyz/keyshade#366]
## Description

We have noticed many of the contributors are using NPM instead of using PNPM. So we want to have a strict restriction over the package manager to be use for this project, and throw error if they are using any other package manager. To only allow PNPM, you can refer to this section of [PNPM Doc](https://pnpm.io/only-allow-pnpm) to set it up for us.

**Comment by rajdip-b** [comment]
We need to make sure that npx works after this.

**Comment by kriptonian1** [comment]
@rajdip-b we don't use npx in pnpm for pnpm it's pnpm dlx

**Comment by rajdip-b** [comment]
> @rajdip-b we don't use `npx` in pnpm for pnpm it's `pnpm dlx` or `pnpx` [docs](https://pnpm.io/cli/dlx)

Yep i know but i think in some places i think we are using npx?

**Comment by kriptonian1** [comment]
Then it should be replaced with `pnpm dlx` because it is not the right way of using it

**Comment by Z-xus** [comment]
It seems there's an ongoing issue which doesn't work for npm but only for yarn https://github.com/pnpm/only-allow/issues/27

**Comment by kriptonian1** [comment]
Let me have a look what it says

**Comment by Z-xus** [comment]
> Assigned the issue to @MelloB1989!

@rajdip-b

**Comment by rajdip-b** [comment]
Hey @MelloB1989, please check if the issues are already assigned or not. You are only allowed to take up issues in case they are not assigned to anyone for FOSS Hack.

**Comment by kriptonian1** [comment]
Maybe we can do use `.npmrc` to make the engine strict. ref : https://www.freecodecamp.org/news/how-to-force-use-yarn-or-npm/

**Comment by Z-xus** [comment]
1. Tested this but it didn't work as intended, perhaps it was version specific. https://www.freecodecamp.org/news/how-to-force-use-yarn-or-npm/

2. I was proposing a shell script to automate the project setup which performs dependency checks, and then followed by step by step commands, although this is quite simple in this project and I feel it's a bit unnecessary since the setup is relatively simple
```
command_exists() {...}
check_dependencies() {...}
install_dependencies() {...}
```

**Comment by Z-xus** [comment]
By unintended I mean, npm and yarn weren't working but that was entirely due to different errors (my guess is that it is some specific `package.json` rule which is only applicable to pnpm):

![image](https://github.com/user-attachments/assets/efcb18c0-b655-4814-a3a5-710939fb717b)

**Comment by kriptonian1** [comment]
ig that is corepack doing it for us, so I feature I don't like about corepack is that it is a bit too strict with the version of package manager

**Comment by kriptonian1** [comment]
you can refer to this to learn how corepack work https://www.totaltypescript.com/how-to-use-corepack

I think we can just use it to restrict users to use pnpm, but the problem with this is it won't even allow to run command if the version of your pnpm dosen't match. so maybe you can look into this

**Comment by muntaxir4** [comment]
> ## Description
> 
> We have noticed many of the contributors are using NPM instead of using PNPM. So we want to have a strict restriction over the package manager to be use for this project, and throw error if they are using any other package manager. To only allow PNPM, you can refer to this section of [PNPM Doc](https://pnpm.io/only-allow-pnpm) to set it up for us.

Although, other package managers will show error due to presence of `workspace:*`. If `just-npm` (https://github.com/pnpm/only-allow/issues/27#issuecomment-1842204593 ) is installed in project's root this will prevent any installation through npm in child packages as well.

**Comment by rajdip-b** [comment]
I'll give this a try

**Comment by muntaxir4** [comment]
> I'll give this a try.
> 
> UPDATE: I tried it, seems like it doesn't work. I guess we should close this issue.

I tested it on my end and it was working fine, except for the `workspace:*` issue which didn't let `npm install` run.
