### ISSUE TITLE
Type error in `platform` while running `pnpm run lint`

### ISSUE THREAD

**Issue by DhairyaMajmudar** [keyshade-xyz/keyshade#371]
**Describe the bug**
Lint scripts failing in platform  

**To Reproduce**
1. run `pnpm run lint` in terminal.

**Expected behavior**
Lint should not fail.

**Screenshots**

![image](https://github.com/user-attachments/assets/51cfd2da-1d42-458f-a9b5-c6795fc52da4)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: Latest

**Comment by rajdip-b** [comment]
Hey bro! Thank you soooo much for opening this issue! We were really stressed with this one. We would be very very glad if you can get a fix for this <3

**Comment by DhairyaMajmudar** [comment]
> Hey bro! Thank you soooo much for opening this issue! We were really stressed with this one. We would be very very glad if you can get a fix for this <3

Sure thing, looking forward to open a PR for this  🚀
