### ISSUE TITLE
Create lint workflow for API

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#38]
## Description
The feature should follow exactly the same flow as `web.yaml`. Please take refs from that. It depends on #33, but can be done easily since some of the code is already present.

To summarize,
- [ ] Create a `api.yaml`
- [ ] Make sure it runs only on pull requests and pushes
- [ ] Also, make sure the entire workflow executes only when changes are made to `apps/api`

**Comment by HarshPatel5940** [comment]
@rajdip-b i would like to work on this!

**Comment by rajdip-b** [comment]
Here you go!
