### ISSUE TITLE
Platform: Build failure of platform app.

### ISSUE THREAD

**Issue by DhairyaMajmudar** [keyshade-xyz/keyshade#384]
**Describe the bug**
Build of platform app is failing as of which the docker image is also not able to be built 

**To Reproduce**
1. run `pnpm run build:platform` in terminal.

**Expected behavior**
Build should not be failing since its crucial for deployment. 

**Screenshots**
![Screenshot from 2024-07-27 20-15-59](https://github.com/user-attachments/assets/83861243-7bb9-4d99-8902-ee837c32afbe)

![image](https://github.com/user-attachments/assets/7cfd8f26-2e77-47b4-a317-5cb7c80958f1)

**Desktop (please complete the following information):**
 - OS: Debian 
 - Browser Firefox
 - Version: Latest
 
**Additional context**
There are several reasons for build failures 
1. Incorrect types
2. Problematic exports 
3. Missing type definitions in shadcn components

**Comment by rajdip-b** [comment]
This has been a known issue and has been blocking us to deploy our platform. Any fixes would be really appreciated!

**Comment by DhairyaMajmudar** [comment]
Yep, opening a PR for this : )
