### ISSUE TITLE
API: Add support for url to include page and limit in e2e Tests.

### ISSUE THREAD

**Issue by muntaxir4** [keyshade-xyz/keyshade#392]
## Description
Currently, while adding page and limit to URLS in tests the service modules has to explicitly convert those to numbers. The query params are parsed as strings, since NestJS doesn't covert numeric query parameters to numbers by default.

Type of limit when not explicitly converted during tests:
![image](https://github.com/user-attachments/assets/849e5ffd-4c6b-4418-9e4a-868406e0c95c)

## Solution
Initialize app with globalPipe using  QueryTransformPipe. Finally, remove those explicit conversions.
![image](https://github.com/user-attachments/assets/bd0b3dbe-8c34-4174-a1aa-3a533f1a792f)

## Alternatives
Directly, using QueryTranformPipe at required controllers. Eg: `@Query('limit', QueryTransformPipe)`

##  Affected e2e modules 
Modules that are using page and limit: `environment.e2e.spec.ts`, `project.e2e.spec.ts`, `workspacee2e.spec.ts`, `workspace-role.e2e.spec.ts`, `secret.e2e.spec.ts`, `variable.e2e.spec.ts`, `event.e2e.spec.ts`

**Comment by rajdip-b** [comment]
You can get started with this ASAP!

**Comment by muntaxir4** [comment]
> You can get started with this ASAP!

Sure, on it.

**Comment by muntaxir4** [comment]
@rajdip-b This is fixed for each module with these PRs https://github.com/keyshade-xyz/keyshade/pull/382 https://github.com/keyshade-xyz/keyshade/pull/387 https://github.com/keyshade-xyz/keyshade/pull/388 https://github.com/keyshade-xyz/keyshade/pull/389 https://github.com/keyshade-xyz/keyshade/pull/390 https://github.com/keyshade-xyz/keyshade/pull/391 https://github.com/keyshade-xyz/keyshade/pull/393 #394 .
