### ISSUE TITLE
[User] Log in using Google

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#4]
Users should be able to log into our platform using Google. We will be scraping off the following things from their account:
- email
- name
- profile picture

**Comment by Abbhiishek** [comment]
I would love to work on this

**Comment by rajdip-b** [comment]
@Abbhiishek  Hey man, that's really great! Would you like to pick up #1 first or this?

**Comment by Abbhiishek** [comment]
Let's start with the first issue

**Comment by rajdip-b** [comment]
Assigning this to you! Be sure to drop into the Discord channel to have a convo about this (or maybe open a ticket)?

**Comment by rajdip-b** [comment]
Hey @Abbhiishek, would be nice to know if you understand the flow or not! Plus, updates about this progress as and when you make it would be much  @appreciated.

**Comment by rajdip-b** [comment]
Ah! my bad! I didn't see your comment properly, :( I'll assign you the first issue!

**Comment by Abbhiishek** [comment]
@rajdip-b ✌️

**Comment by HarshPatel5940** [comment]
> [!Note]
> If someone is proceeding to solve this, also make it optional. 
> addressing this with respect to #107

**Comment by rajdip-b** [comment]
@HarshPatel5940 I belive no one is working on this, so you might very well take this up. Also, you can address the issue of #107 in the same PR.

**Comment by HarshPatel5940** [comment]
> @HarshPatel5940 I belive no one is working on this, so you might very well take this up. Also, you can address the issue of #107 in the same PR.

I wanted to wait for a few hours as I am calling for new contributors so they can get started with what's going on with API the least.

I will start working if someone does not take it up by tonight.

**Comment by rajdip-b** [comment]
> I wanted to wait for a few hours as I am calling for new contributors so they can get started with what's going on with API the least.

This would be awesome!

> I will start working if someone does not take it up by tonight.

whenever you feel like

**Comment by HarshPatel5940** [comment]
@risv1 check these steps out to make google optional https://github.com/keyshade-xyz/keyshade/pull/112#pullrequestreview-1865977568 

make a Draft PR, as soon as time permits.

**Comment by rajdip-b** [comment]
hey folks @HarshPatel5940 @risv1 any updates on this?

**Comment by rajdip-b** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Google OAuth](https://trello.com/c/fCJioG1R/4-add-google-oauth)

**Comment by risv1** [comment]
Yes, sorry for the lack of updates, you've provided the link for Trello's API, would you like me to proceed with that or use Passport as mentioned earlier?

**Comment by rajdip-b** [comment]
Haha I just tracked this issue using trello so it showed up! Keep using passport :)

**Comment by risv1** [comment]
Oh alright thanks for the clarification 👍:)

**Comment by HarshPatel5940** [comment]
@risv1 Give us a tentative deadline, so even you will be responsible with the dates.

**Comment by rajdip-b** [comment]
Yeah that will definitely help us track it. Considering the fact that @HarshPatel5940 covered most of it, it should be a cakewalk.

#98 check this PR.

**Comment by risv1** [comment]
Yeah sure I'll get started with it, will try to get it done asap.
