### ISSUE TITLE
API: Add endpoint to fetch all workspace invitations for a user

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#404]
## Description

We would like to add an endpoint to fetch all the active workspace invitations that the user has.

## Solution

- Add an endpoint `/api/workspace/invitations` under `workspace.controller.ts`
- Add a function named `getAllWorkspaceInvitations` in `workspace.service.ts` that implements the logic. The response should be paginated
- Add proper tests in `workspace.e2e.spec.ts`

**Comment by sankettank66** [comment]
Hello @rajdip-b 
Could you assign me this task?

**Comment by rajdip-b** [comment]
Sure!

**Comment by rajdip-b** [comment]
@sankettank66 any progress?

**Comment by rashmod** [comment]
@sankettank66 Are you still working on this, or should I take it on?

**Comment by rajdip-b** [comment]
@rashmod Feel free to take this up.

**Comment by bansal-harsh-2504** [comment]
@rajdip-b  Do I need to create a prisma model for workspaceInvitation ?

**Comment by rajdip-b** [comment]
No, you will be just using the existing tables.

**Comment by rajdip-b** [comment]
Unassigning due to inactivity

**Comment by rajdip-b** [comment]
@muntaxir4 i think we can safely close this one since we are tracking it in #550
