### ISSUE TITLE
PLATFORM: Replace `localStorage` with Jotai

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#409]
Scope of change:

https://github.com/keyshade-xyz/keyshade/blob/2b54421b1b8080dcb38d8c1f0c2c473512a0821f/apps/platform/src/lib/workspace-storage.ts#L3-L22

**Comment by rajdip-b** [comment]
@DhairyaMajmudar You can start with this one.

**Comment by DhairyaMajmudar** [comment]
Thank you : )

**Comment by rajdip-b** [comment]
Hey @DhairyaMajmudar, are you still on this?

**Comment by kriptonian1** [comment]
This is an invalid issue
