### ISSUE TITLE
Make landing page mobile responsive

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#41]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/keyshade-xyz/keyshade/assets/83924254/caa1ea86-fed8-4b1b-8bcb-6f827927034e)
Current behavior of the landing page is not up to the mark. Need to be responsive in mobile ui.

**Comment by rajdip-b** [comment]
@SRINJAYDASGUPTA-Git imma assign this to you real quick

**Comment by SRINJAYDASGUPTA-Git** [comment]
yeah I am on it
ASSIGN

**Comment by rajdip-b** [comment]
@kriptonian1 do you wanna do this?

**Comment by kriptonian1** [comment]
For sure

**Comment by SRINJAYDASGUPTA-Git** [comment]
ASSIGN
