### ISSUE TITLE
PLATFORM: Test failing due to strict null check implementation

### ISSUE THREAD

**Issue by unamdev0** [keyshade-xyz/keyshade#412]
**Describe the bug**
Tests are failing due to strict null check implementation done in [this](https://github.com/keyshade-xyz/keyshade/commit/072254f20c05fe0f2b2d099787e0562dc806394a) commit

**To Reproduce**
Run `pnpm run test`

**Expected behavior**
All tests should pass successfully

**Screenshots**
<img width="1016" alt="Screenshot 2024-09-06 at 7 07 51 PM" src="https://github.com/user-attachments/assets/06a4d145-573c-4bf3-a049-8167cffb49f8">

**Comment by rajdip-b** [comment]
Hi! Thanks for opening this issue! We have a LOT of inconsistencies across our platform package since it's not yet actively developed. 

We have quite a few errors in this package. Would be very glad if you can come up with the fixes!

**Comment by unamdev0** [comment]
Gladly, my solution would be to apply optional chaining for the time being at all these critical places,but since that's what was there before and was removed, can you please suggest any other solution which can be done

**Comment by rajdip-b** [comment]
> Gladly, my solution would be to apply optional chaining for the time being at all these critical places,but since that's what was there before and was removed, can you please suggest any other solution which can be done

I think pretty much any changes that I made were to make sure the lints passed back then. So if bringing them back helps preventing this issue, I would be glad to accept the solution.

**Comment by unamdev0** [comment]
Cool, making the required changes
