### ISSUE TITLE
API: Update the functionality by which slugs are generated for entities

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#416]
## Description

Slugs are associated to the following entities:
- Workspace
- Workspace Role
- Integration
- API Key
- Project
- Environment
- Secret
- Variable

Whenever any of these entities are created, we associate a `slug` to it. The slug is based upon the name of the entity. Similarly, if the name is updated, we update the slug aswell.

Here is the code that is responsible for the same:
https://github.com/keyshade-xyz/keyshade/blob/89e2fccc390771c925ea9d1c4ede8270ec6e5a80/apps/api/src/common/slug-generator.ts#L11-L25

Right now, it generates a slug based out of these conditions:
- Convert name to lowecase
- Replace spaces(" ") with hyphens(-)
- Append a random charset(a-z0-9) to the name

What we want to do is, update the way the charset is associated. Ideally, instead of generating the charset randomly, we would like to increment it based upon existing knowledge.

## Solution

Let's say you have been given a variable named `PORT`. We would like to save the name using this format: `name-<incremental charset>`.

Essentially what this means it, we might have a number of variables across different projects that might be named `PORT` but we want to identify each `PORT` variable by its slug uniquely. So, this pattern would create multiple slugs in the following format: `port-0`, ..., `port-9`, `port-a`, ... `port-z`, `port-00`, ... and so on.

- Convert it to lowercase
- Replace spaces and underscores with hyphens
- We query the database for this name using the regex pattern of `^port-[\d\w]*$`, sorting the results in descending. The pattern translates to "any name that starts with `port-` and ends with a lowercase alphanumeric charset".
- If one does not exist, we save the slug as `port-0`.
- Although, if a name already exists, we increment the name and save it. Say the last name is `port-44ab`. Then the name of our new port variable would be `port-44ac`.

## Additional context

Refer to #415 to understand how slugs were implemented

**Comment by Nil2000** [comment]
Since the slug check is dependent upon entityType, we need to generateSlug specific to each entityType. Is it?
Correct me if I am wrong

**Comment by rajdip-b** [comment]
https://github.com/keyshade-xyz/keyshade/blob/edfbce068dc0c3d23a92ce3a9d69c06f8457b7d8/apps/api/src/common/slug-generator.ts#L92

If you take a look in this function, you would find that the only dependency on the entity type is to check for uniqueness, and not for naming convention. Also, that check is already in place. You would just need to update the `generateSlug` method. Hope that makes sense

**Comment by Prakhargarg-2010196** [comment]
Hi,has this issue been already picked up? I am new to open-source and would like to take it up if possible ?

**Comment by Prakhargarg-2010196** [comment]
Okay let me see if there is some other issue i can deal with Thanks for quick response.
