### ISSUE TITLE
Create scheduler to delete expired OTPs

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#42]
## Description

The OTPs have a validity of 5 minutes now. We would like a scheduled task to run every 1 hour and clean up such OTPs

**Comment by rajdip-b** [comment]
@sharmaudit124 okei so, in this one, I would like you to create a scheduled function that calls itself every hour. you can refer to nestjs scheduling docs to understand how its done. The scheduled function would go through all the otps, and delete the ones that are expired

**Comment by lakshay-saini-au8** [comment]
@rajdip-b can I work on this issue

**Comment by rajdip-b** [comment]
Hey sure!! @lakshay-saini-au8
