### ISSUE TITLE
WEB: Website logo cut off or overlaps in footer

### ISSUE THREAD

**Issue by AadiVerma** [keyshade-xyz/keyshade#433]
**Describe the bug**
The website name is either partially displayed or gets overridden by other elements in the footer section

**To Reproduce**
1. Open the website
2. Scroll down to the footer section.
3. Observe that the website name is cut off or overlaps with other footer content.

**Expected behavior**
The website name should be fully visible in the footer section without being truncated or overridden, regardless of screen size.

**Screenshots**
![Screenshot 2024-09-15 132849](https://github.com/user-attachments/assets/c79f2768-df47-47df-a7d3-b392edca4895)

**Comment by rajdip-b** [comment]
Hmm, looks legit. Would you be able to come up with a fix?

**Comment by AadiVerma** [comment]
> Hmm, looks legit. Would you be able to come up with a fix?


I can definitely try.

**Comment by m7md-Y-3mra** [comment]
I need to work to it, assign to me

**Comment by rajdip-b** [comment]
Ah boy, in this case I'm not sure whom I should assign this to. Needless to say there isn't any competition. I would recommend you folks to have a chat among yourself and decode who gets to implement it.

**Comment by AadiVerma** [comment]
Np, I have no issues he can continue

**Comment by m7md-Y-3mra** [comment]
Hi @AadiVerma @rajdip-b,

I've resolved the issue with the footer where the website name was cut off or overlapping with other elements. However, I've noticed a new issue with horizontal scrolling on the website.

Should I proceed with investigating and fixing the horizontal scroll issue, or would you prefer to handle it differently?

Looking forward to your guidance!

Thanks.

**Comment by rajdip-b** [comment]
You can raise a new issue about it and self assign yourself. It helps us in keeping track of things!

**Comment by m7md-Y-3mra** [comment]
I've created a new issue for the horizontal scrolling problem: https://github.com/keyshade-xyz/keyshade/issues/437

Could you please assign it to me?

**Comment by rajdip-b** [comment]
Hey @m7md-Y-3mra, unfortunately someone just started attempting that. I won't be able to unassign them. From the next issues onwards, you would just need to comment /attempt on the issue description and you will be auto assigned!

**Comment by m7md-Y-3mra** [comment]
@rajdip-b Hi I did the PR #444 . If there is anything then let me know. Thanks

**Comment by AadiVerma** [comment]
Still Logo is cut off 
![image](https://github.com/user-attachments/assets/21625117-de8c-4335-a9b5-449fd7fe3b2b)
