### ISSUE TITLE
Horizontal Scrolling Issue on the Website

### ISSUE THREAD

**Issue by m7md-Y-3mra** [keyshade-xyz/keyshade#437]
Description: I have resolved the issue with the footer where the website name was cut off or overlapping with other elements. However, I've identified a new problem with horizontal scrolling on the website.

To Reproduce:

1. Open the website.

2. Observe the horizontal scrolling across different screen sizes.

Expected Behavior: The website should not have horizontal scrolling and should fit within the viewport without extending beyond it.

**Comment by Samaresh-Das** [comment]
I would like to work on this. May I?

**Comment by Samaresh-Das** [comment]
/attempt I would like to work on this. May I?
From first glance it feels like I need to make the site responsive for tablet also. The site is not completely compatible with tablet sizes.

**Comment by Samaresh-Das** [comment]
@rajdip-b In the test cases, some are failing. Can it be because I didn't setup the API and SMTP credentials as my task was only to work with the UI. Or I have to setup the API too?
![image](https://github.com/user-attachments/assets/062fef25-df35-4998-8193-dfe222e9a441)

**Comment by rajdip-b** [comment]
Every package has its own suite of scripts. The pattern is `<package>:<script>`. You can look that up in package.json.

If you are getting these errors while committing, use `--no-verify` along with your commit to skip tests.

**Comment by Samaresh-Das** [comment]
@rajdip-b Hi I did the PR #440 . If there is anything then let me know. Thanks
