### ISSUE TITLE
Fix lint ERROR

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#45]
## Description
![image](https://github.com/keyshade-xyz/keyshade/assets/83924254/560ed4c7-ce7f-4caa-bcb7-326ccc757362)
![image](https://github.com/keyshade-xyz/keyshade/assets/83924254/715b394b-f30a-447c-af06-ab99ac5c03b7)

Currently, unused imports and variables show up as ERROR. This isn't expected. This is the expected outcome:
- Unused imports and variables show up as WARN, not ERROR
- During the lint phase, we fail the check if such unused dependencies are found.

**Comment by HarshPatel5940** [comment]
@rajdip-b willing to work on this.

**Comment by rajdip-b** [comment]
Here you go!

**Comment by HarshPatel5940** [comment]
@rajdip-b we can close this as completed.

**Comment by rajdip-b** [comment]
Ah, yes
