### ISSUE TITLE
DOCS: Add docs for `project` in CLI

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#456]
## Description

Add documentation for the `project` command in our CLI.

## Solution

- Create a file named `project.md` in [here](https://github.com/keyshade-xyz/keyshade/tree/develop/docs/cli)
- Check the [commands](https://github.com/keyshade-xyz/keyshade/blob/develop/apps/cli/src/commands/project.command.ts) and put up the docs accordingly
- You can take reference from [here](https://docs.keyshade.xyz/cli/profile)

**Comment by YuvalBubnovsky** [comment]
Can I please get this issue assigned to me?

**Comment by YuvalBubnovsky** [comment]
/attempt

Going to take a crack at this :)

**Comment by Allan2000-Git** [comment]
@YuvalBubnovsky can you take one issue at a time?
