### ISSUE TITLE
DOCS: Add docs for `environment` in CLI

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#457]
## Description

Add documentation for the `environment` command in our CLI.

## Solution

- Create a file named `environment.md` in [here](https://github.com/keyshade-xyz/keyshade/tree/develop/docs/cli)
- Check the [commands](https://github.com/keyshade-xyz/keyshade/blob/develop/apps/cli/src/commands/environment.command.ts) and put up the docs accordingly
- You can take reference from [here](https://docs.keyshade.xyz/cli/profile)

**Comment by Allan2000-Git** [comment]
/attempt I'd like to work on this issue.

**Comment by Allan2000-Git** [comment]
@rajdip-b Can you review the PR? Let me know if any changes are required.
