### ISSUE TITLE
DOCS: Add docs for `workspace` in CLI

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#458]
## Description

Add documentation for the `workspace` command in our CLI.

## Solution

- Create a file named `workspace.md` in [here](https://github.com/keyshade-xyz/keyshade/tree/develop/docs/cli)
- Check the [commands](https://github.com/keyshade-xyz/keyshade/blob/develop/apps/cli/src/commands/workspace.command.ts) and put up the docs accordingly
- You can take reference from [here](https://docs.keyshade.xyz/cli/profile)

**Comment by YuvalBubnovsky** [comment]
Can I please get this issue assigned to me?

**Comment by YuvalBubnovsky** [comment]
/attempt

Going to take a crack at this :)
