### ISSUE TITLE
DOCS: Add docs for `scan` in CLI

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#459]
## Description

Add documentation for the `scan` command in our CLI.

## Solution

- Create a file named `scan.md` in [here](https://github.com/keyshade-xyz/keyshade/tree/develop/docs/cli)
- Check the [commands](https://github.com/keyshade-xyz/keyshade/blob/develop/apps/cli/src/commands/scan.command.ts) and put up the docs accordingly
- You can take reference from [here](https://docs.keyshade.xyz/cli/profile)

**Comment by Allan2000-Git** [comment]
/attempt I'd like to work on this issue.

**Comment by Allan2000-Git** [comment]
@rajdip-b should I add examples to showcase the usage of the command as suggested by the bot?

**Comment by Allan2000-Git** [comment]
@rajdip-b I have added usage example code block. Can you review it?
