### ISSUE TITLE
DOCS: Add page for "Running the Platform"

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#472]
## Description

We need to list the commands and prerequisites regarding how to get the Platform app up and running. Refer to [this](https://docs.keyshade.xyz/contributing-to-keyshade/running-things-locally/running-the-web-app) for motivation.

## Solution

- [ ] Create a file named `running-the-platform.md`
- [ ] Add all of your writeup in here
- [ ] Add the entry in [here](https://github.com/keyshade-xyz/keyshade/blob/develop/docs/SUMMARY.md)

**Comment by Allan2000-Git** [comment]
/attempt I'd love to work on this issue.

**Comment by Allan2000-Git** [comment]
@rajdip-b How will I know the commands? Is it the same as [this](https://github.com/keyshade-xyz/keyshade/blob/develop/docs/contributing-to-keyshade/running-things-locally/running-the-web-app.md) ?

**Comment by rajdip-b** [comment]
Yes! Good catch. I'll do that right now.
