### ISSUE TITLE
PLATFORM: Implement resend OTP flow

### ISSUE THREAD

**Issue by kriptonian1** [keyshade-xyz/keyshade#479]
## Description
In the current `auth` flow, we don't have a resent OTP button, meaning if the OTP times out, you don't have a way to get the OTP. You need to implement the resent OTP in the `/auth/otp`.

## Scope of Work
- You need to implement the UI for resend OTP flow in the [`apps/platform/src/app/auth/otp/page.tsx`](https://github.com/keyshade-xyz/keyshade/blob/develop/apps/platform/src/app/auth/otp/page.tsx) page.
- When the resent OTP button is clicked, you need to call `{BASE_URL}/api/auth/send-otp/:email` endpoint
## URLs you need
- Figma UI for resend OTP flow [link](https://www.figma.com/design/Du3qt5NWbbnfMgtU5CQYCU/Keyshade-UI?node-id=862-489&node-type=canvas&t=PmGAEhY7HdEKfFGT-0)
- Postman URL for `{BASE_URL}/api/auth/send-otp/:email` [link](https://www.postman.com/keyshade/workspace/keyshade/api/a31bdb66-69e3-469b-afb4-f2051385e634/request/32733901-3db2069c-6157-4ee2-a64f-f053f380646a?action=share&source=copy-link&creator=32744470&active-environment=8fc04ef8-aeca-488d-828a-095b724fb9de)

**Comment by kriptonian1** [comment]
@Prakhargarg-2010196 would you like to take this issue?

**Comment by Prakhargarg-2010196** [comment]
I guess i had already taken both the Ui and backend for this feature the api endpoint for this feature with throttler have been pushed as a PR which @rajdip-b has approved. The Ui i will start working on this week. 
So yes would be happy to take this

**Comment by Sarveshk76** [comment]
Hi @kriptonian1 , I would like to work on this issue

**Comment by kriptonian1** [comment]
> Hi @kriptonian1 , I would like to work on this issue
Sure man 🙌

**Comment by Prakhargarg-2010196** [comment]
@kriptonian1 So should I not continue working on this?

**Comment by rajdip-b** [comment]
> Hi @kriptonian1 , I would like to work on this issue

Hey man, sadly this issue was already taken by @Prakhargarg-2010196. The assignment was missing!

**Comment by Prakhargarg-2010196** [comment]
@kriptonian1 I think so description needs some modifications as #326 mentions a new endpoint for resend-otp (although) internally might be using the same function as send otp.

**Comment by kriptonian1** [comment]
@rajdip-b what endpoint should we go with ?

**Comment by Prakhargarg-2010196** [comment]
> @rajdip-b what endpoint should we go with ?
> 
resend-otp/:email as mentioned in #326

**Comment by kriptonian1** [comment]
> > @rajdip-b what endpoint should we go with ?
> 
> resend-otp/:email as mentioned in #326

Last I had a chat with him, he asked to use send-otp endpoint

**Comment by Prakhargarg-2010196** [comment]
> > > @rajdip-b what endpoint should we go with ?
> > 
> > resend-otp/:email as mentioned in #326
> 
> Last I had a chat with him, he asked to use `send-otp` endpoint

@rajdip-b what should be done ?

**Comment by rajdip-b** [comment]
> > > @rajdip-b what endpoint should we go with ?
> > 
> > 
> > resend-otp/:email as mentioned in #326
> 
> Last I had a chat with him, he asked to use `send-otp` endpoint

Sending is for one time. Currently we are using it all the time, but ideally we need to move to `resend-otp`

**Comment by Prakhargarg-2010196** [comment]
Should the link be disabled until the throttle limit or we would depend on the errror coming from the throttler to notify the user ?

**Comment by kriptonian1** [comment]
Hey @Prakhargarg-2010196, the PR LGTM, I have added a suggestion, once you fix it, it will be good to merge
