### ISSUE TITLE
docs: setting things up is not proper 

### ISSUE THREAD

**Issue by ezhil56x** [keyshade-xyz/keyshade#48]
**Describe the bug**
Setting things up page in docs is not proper, wrong markdown syntax

**To Reproduce**
1. Go to [https://docs.keyshade.xyz/contributing-to-keyshade/setting-things-up](https://docs.keyshade.xyz/contributing-to-keyshade/setting-things-up)

**Screenshots**

![image](https://github.com/keyshade-xyz/keyshade/assets/103899034/be089281-15fe-476f-adc6-44e7e7c5f7d9)

**I am up to work on this! ✋🏻, but couldn't find the docs in the repo**

**Comment by rajdip-b** [comment]
Hey!!! We have migrated everything to docs.keyshade.xyz. do check it out once, and in case you find anything wrong or missing, do let us know!!

**Comment by rajdip-b** [comment]
Thanks for pointing this our man! Unfortunately gitbook is closed to org folks only :/ I'll still give it a look and see if public contributions can be made

**Comment by rajdip-b** [comment]
Hey @ezhil56x I have added the docs folder. Also, I have set up a bidirectional binding with GitBook. So, in case you find any more discrepancies, please feel free to submit a PR!
