### ISSUE TITLE
PLATFORM: Update the empty state for dashboard based on new Figma design

### ISSUE THREAD

**Issue by kriptonian1** [keyshade-xyz/keyshade#485]
## Description
You need to update the current empty dashboard state with the current empty state design in Figma.

## Scope of Work
You need to update the part of the codebase with the [current Figma design](https://www.figma.com/design/Du3qt5NWbbnfMgtU5CQYCU/Keyshade-UI?node-id=875-6883&node-type=frame&t=0d00kh02HblhIGe3-0)
https://github.com/keyshade-xyz/keyshade/blob/256d65974babd17d525ce2a41a5e17136e6ac12e/apps/platform/src/app/(main)/page.tsx#L176-L178

**Comment by poswalsameer** [comment]
Hi @kriptonian1, can I get the link for the figma file?

**Comment by dev-palwar** [comment]
hey @Aleesssino if its still open then can i work on it?

**Comment by Aleesssino** [comment]
Hi @dev-palwar ...Yes, feel free to take it on. I was planning to pass it along since I ran into some errors and haven’t had time to resolve them. Thanks for picking it up!

**Comment by rajdip-b** [comment]
Thanks for the prompt response @Aleesssino!

All yours @dev-palwar

**Comment by dev-palwar** [comment]
@rajdip-b , I don’t see a dedicated directory for icons in the codebase. Are we currently hosting them on a cloud service for usage, or are we planning to create our own library?
