### ISSUE TITLE
Missing Documentation on Resetting the Local Prisma Database

### ISSUE THREAD

**Issue by career-yashaswee** [keyshade-xyz/keyshade#495]
### Missing Documentation on Resetting the Local Prisma Database

**Describe the bug**
The current Keyshade documentation lacks instructions on how to reset the local Prisma database. This omission makes it difficult for contributors to test the platform effectively and isolate problems in a clean database state.

**To Reproduce**
Steps to identify the issue:
1. Go to the [Running the API](https://docs.keyshade.xyz/contributing-to-keyshade/running-things-locally/running-the-api) section in the documentation.
2. Notice there is no information provided on how to reset the Prisma database.

**Expected behavior**
The documentation should include clear steps to reset the local Prisma database for testing and troubleshooting purposes. This will help contributors start with a clean slate when isolating issues.

**Screenshots**

KeyShade without any comments on how to reset the database
<img width="1435" alt="image" src="https://github.com/user-attachments/assets/6c812006-aeea-423b-a665-8d3fc665d692">

ToolJet with a comment on "how to reset your local database"
<img width="827" alt="image" src="https://github.com/user-attachments/assets/085726bf-427d-4a6e-a0b1-86c766844b87">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Browser : chrome
 - Version : 22

**Smartphone (please complete the following information):**
NA

**Additional context**
For reference, an open-source project Tooljet provides a clear explanation of how to reset their databases in their documentation. You can check it out [here](https://docs.tooljet.com/docs/contributing-guide/setup/codespaces/#4-set-up-database).

**Comment by rajdip-b** [comment]
@career-yashaswee I get that you created the issue yourself, but then @Aleesssino made the first attempt. So it would be fair to let him take this once, since it has been quite a few hours since he has started. If he drops it, you can take it up.

**Comment by rajdip-b** [comment]
Also, thanks for opening this issue. This looks like a really good addition.

**Comment by career-yashaswee** [comment]
Ohh Sure, then I would love to create a new issue on how the issue assignment system works.
The GitHub Bot should validate the users on the assignment and restrict or assign based on prior knowledge of the user.

**Comment by rajdip-b** [comment]
This would be a great addition I believe.
