### ISSUE TITLE
WEB:Enlargement of Team Cards 

### ISSUE THREAD

**Issue by Luciferlocas** [keyshade-xyz/keyshade#498]
## Description
The current design of the team cards displayed on the website is too small, making it difficult for users to fully appreciate the individual team members, which overall is not looking good on the page.

## Solution
I propose enlarging the team cards to enhance their visual presence on the page. This change would highlight each team member more effectively and improve the overall aesthetics of the website.

## Alternatives
As an alternative, we could explore redesigning the layout to accommodate larger cards without compromising responsiveness. However, I believe that simply enlarging the cards would provide a more immediate benefit.

## Additional context
Here are the current and proposed designs for better illustration:

Current :
![image](https://github.com/user-attachments/assets/4ae34306-e037-483c-9333-ddef5fc24915)

Proposed :
![image](https://github.com/user-attachments/assets/ce7d56cb-4cea-42c4-b10b-03336afb99ad)

These enhancements would significantly improve user experience and appreciation for the teams.

**Comment by rajdip-b** [comment]
@Aleesssino before you come up with the solution, we would like to verify the design necessity first. So please hold on for a bit.

@kriptonian1 do you feel this change would be good?

**Comment by rajdip-b** [comment]
@kriptonian1 hey man, thoughts on this?

**Comment by kriptonian1** [comment]
It was a design decision to go with small cards

**Comment by rajdip-b** [comment]
So we can close this issue. @Luciferlocas thanks for opening this issue, but since this was pre-planned I don't think we will be changing it!
