### ISSUE TITLE
PLATFORM: No Visual Feedback for Internet Connection Status

### ISSUE THREAD

**Issue by career-yashaswee** [keyshade-xyz/keyshade#499]
### No Visual Feedback for Internet Connection Status

**Describe the bug**  
The platform currently lacks visual feedback to indicate the user's internet connection status. There is no notification or visual indicator when the user is offline, which may lead to confusion when requests are made without a stable connection. The platform should display a red bar above the interface indicating that the user is offline and prompting them to reconnect before making any further requests.

**To Reproduce**  
1. Access the platform application.
2. Turn off your internet connection.
3. Observe that the platform gives no feedback on the internet connection status.

**Expected behavior**  
- A **red bar** should appear at the top of the interface when the user is offline, notifying them that they need to reconnect to the internet before making further requests.
- A **toaster notification** should also appear to notify the user that they are not connected to the internet.
- Once the user reconnects to the internet, another **toaster notification** should inform them they are back online, and the interface should **reset and sync the platform** with its current state.

**Screenshots**  
Check this Video out!
https://www.loom.com/share/f085a88f7ef6476fb6360e4d8bb22ffc?sid=f6aa37d2-612f-40f7-aae9-ca94579f39ca

**Desktop (please complete the following information):**
- OS: macOS Sonoma
- Browser: Chrome
- Version: -

**Smartphone (please complete the following information):**  
NA

**Additional context**  
This feature would prevent users from attempting actions while disconnected and ensure the platform automatically updates once the internet connection is restored.

**Comment by rajdip-b** [comment]
Looks real nice to me!

**Comment by dev-palwar** [comment]
Hey @career-yashaswee  Just wanted to check if you're still working on this. If not, please let me know, and I'd be happy to take it on.

**Comment by Allan2000-Git** [comment]
/attempt I'd love to take a crack on this issue.
