### ISSUE TITLE
Create a mail template for OTP

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#51]
## Description

The current OTP mail looks boring TBH. Make a more vibrant OTP mail.
![image](https://github.com/keyshade-xyz/keyshade/assets/83924254/facf1117-f0fd-4390-b4d9-26dd1408f5a3)

## Tasks
- [x] Create the template in Figma
- [ ] Export the code and set it in the present mail code

**Comment by darksaiii** [comment]
Created template in figma

**Comment by Allan2000-Git** [comment]
/attempt I'd love to work on this issue.
