### ISSUE TITLE
Replace `pnpx` with `pnpm dlx`

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#510]
## Description

A lot of commands are still using `pnpx`. Update them to use `pnpm dlx`

## Solution

You would need to make the changes here:
- https://github.com/keyshade-xyz/keyshade/blob/1b4bf2f6b89fa981e2a008f9b7e508b578c55a95/.github/workflows/release.yml#L33
- https://github.com/keyshade-xyz/keyshade/blob/1b4bf2f6b89fa981e2a008f9b7e508b578c55a95/apps/api/package.json#L13-L17

**Comment by tharikashree** [comment]
Hey can i work on this

**Comment by rajdip-b** [comment]
sure
