### ISSUE TITLE
API-CLIENT: Unable to infer type when using the package in client apps

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#512]
**Describe the bug**

The API Client package is used by other clients (in the apps folder) to call the API. Currently, we are facing the issue where the client apps are not able to infer the types, even though the API Client package has a well-defined type. We would like someone to investigate the issue.

![image](https://github.com/user-attachments/assets/a9cb193e-2d4c-4dc3-9008-fc3162b0c607)

Use this link for reference: https://stackoverflow.com/questions/56018167/typescript-does-not-copy-d-ts-files-to-build

**Comment by Avik-creator** [comment]
Can I pick this up? @rajdip-b

**Comment by rajdip-b** [comment]
Hey bruh! Sure go ahead.

**Comment by muntaxir4** [comment]
The error for authController is fixed when migrated to `.ts` https://github.com/keyshade-xyz/keyshade/blob/46eb5c5aeee76f60015e65174e9cb9ea97f5e771/packages/api-client/src/types/auth.types.ts#L1C1-L4C38.

Once, Issue #519 is resolved by moving the types to just `.ts`, this will be fixed.

**Comment by Avik-creator** [comment]
I guess you then solved it. Today I was going to sit for the error

**Comment by rajdip-b** [comment]
Yeah, the timeline got messed up a bit. We didn't realize these were dependent issues!

**Comment by rajdip-b** [comment]
This is fixed! Closing the issue.
