### ISSUE TITLE
PLATFORM: Fix Zod error in workspace

### ISSUE THREAD

**Issue by kriptonian1** [keyshade-xyz/keyshade#518]
## Description
Right now if you open the app in the workspace it will say no workspace, and this is because of the zod validation error as the data from the backend does not match the frontend.
You need to align the zod type with the backend response.
https://github.com/keyshade-xyz/keyshade/blob/46eb5c5aeee76f60015e65174e9cb9ea97f5e771/apps/platform/src/types/index.ts#L14-L24

**Comment by rajdip-b** [comment]
@kriptonian1 we already have the schemas in `packages/schema`. Please use that. We don't want to redefine this everywhere. Also, we don't want to check the response type from the backend.

**Comment by kriptonian1** [comment]
We should check the response to make sure the UI is aligned with response

**Comment by rajdip-b** [comment]
In what aspects?

**Comment by kriptonian1** [comment]
<img width="687" alt="image" src="https://github.com/user-attachments/assets/26a616b7-9d95-4864-b74f-85a4ada30720">
as you can see here on the left you have the response from the API and on the right this is the type defined by the api-client

**Comment by kriptonian1** [comment]
also, I will insist on validating API response using zod because it's a good practice

**Comment by rajdip-b** [comment]
> <img alt="image" width="687" src="https://private-user-images.githubusercontent.com/74916308/383017131-26a616b7-9d95-4864-b74f-85a4ada30720.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3ODQ5MjQsIm5iZiI6MTczMDc4NDYyNCwicGF0aCI6Ii83NDkxNjMwOC8zODMwMTcxMzEtMjZhNjE2YjctOWQ5NS00ODY0LWI3NGYtODVhNGFkYTMwNzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA1MzAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZTZkYWZhYTRhNzE1NjkzZTY0MWI2ODA5ZDI1ZTY3OTUyMWZmNTI1OTk1MzUwZDg3MWQ2NGU2ZjE0OGVkZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HRKuA7sCu8HOsqgmu3AgzqI_eN7q6xNe-kX-IzqfCXg"> as you can see here on the left you have the response from the API and on the right this is the type defined by the api-client

You are comparing a workspace with an environment type

**Comment by kriptonian1** [comment]
got it, now we just shouldn't do type we should do zod type, that a good practice

**Comment by rajdip-b** [comment]
In that case, there are a few things we need to do so that we don't re-write the types everywhere. The response from the API varies for every request. You can check that in the `api-client` package. IMO, it would be best to define the zod schemas for these inside `schema`, and then use the `zod infer schema` structure to get the response types in `api-client`. That way, we are reusing the response schema in `api-client`, `cli` and `platform`.

**Comment by poswalsameer** [comment]
> In what aspects?

In `packages/schema/src/workspace.ts`, the schema for CreateWorkspace looks like this, while the response is something else.

![Screenshot (241)](https://github.com/user-attachments/assets/28fd206f-d4f0-46e3-b246-2cbce1432ff8)

**Comment by rajdip-b** [comment]
@muntaxir4 is already on it. Just hold up for a while before getting started with this. Once he is done you won't need to bother with the types anymore.

**Comment by poswalsameer** [comment]
> @muntaxir4 is already on it. Just hold up for a while before getting started with this. Once he is done you won't need to bother with the types anymore.

Actually, I have found the actual issue.

Here in this image below, we are getting all the workspaces by hitting the API, and expecting the type Workspace which is initialized inside `platform/src/types/index.ts` using zod. So, the change has to happen in this file, need to align it with the response. Shared the same thing with @kriptonian1 too.

![Screenshot (245)](https://github.com/user-attachments/assets/d30ab8bd-49ad-43de-9580-d279725674dd)

**Comment by rajdip-b** [comment]
@kriptonian1 can brief you about the fix that Muntasir is working on. None of the client apps would have to worry about zod once that feature gets implemented.

**Comment by kriptonian1** [comment]
@rajdip-b I have brief him about it on discord

**Comment by poswalsameer** [comment]
> @kriptonian1 can brief you about the fix that Muntasir is working on. None of the client apps would have to worry about zod once that feature gets implemented.

yep, heard from him.
