### ISSUE TITLE
PACKAGE: Update `schema` package to contain all the zod types

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#519]
## Description

The `schema` package is meant to be used by all the other apps and packages. We would like it to have the type definitions and the zod schemas.

The `api-client` is currently holding the request and response types. We would like to move them out to `schema` package.

## Solution

For every module, we would like to do this:
- Create a folder with the module name in `schema`. For example `environment`, `project`, etc.
- Add 2 files in here: `modulename.ts` and `modulename.types.ts`.
- `modulename.ts` would have the following zod schemas: the module base type, all request types, all response types.
- `modulename.types.ts` would be exporting the inferred types
- The top level `index.ts` file would be exporting everything.
- Update `api-client` package to use the types from `schema`.

## Tasks

Here are the modules which we need to work on:
- [x] Auth (#532)
- [x] User (#535)
- [x] Workspace (#520)
- [x] Project (#538)
- [x] Environment (#538)
- [x] Secret (#539)
- [x] Variable (#545)
- [x] Event (#546)
- [x] Integration (#547)
- [x] API Key (#557)
- [x] Workspace Role (#568)
- [x] Workspace Membership (#569)

**Comment by rajdip-b** [comment]
@muntaxir4 thanks for the prompt work!

**Comment by rajdip-b** [comment]
@muntaxir4 updated the details

**Comment by muntaxir4** [comment]
> @muntaxir4 thanks for the prompt work!

My pleasure. I will try to implement the 3 more schemas from today onwards.
