### ISSUE TITLE
Auto assign workflow

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#52]
Would like to have a possible way to do the following:

- Contributors can type `/attempt` in any issue comments
- A CI will assign the issue to the commentor if it has not been assigned already, else, will display a message that the action needs the interference of the maintainers

The suggested features should be created in a GitHub Actions file. Preferably, name it `auto-assign.yaml`

It would be a huge plus if you can also update the `CONTRIBUTION.md` with the steps accordingly!

**Comment by lakshay-saini-au8** [comment]
@rajdip-b
