### ISSUE TITLE
SECRET-SCAN: Add test coverage

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#521]
## Description

The secret scan package has tests enabled but it doesn't upload them to codecov when validating. Also, we would like to migrate from mocha to jest.

## Solution

- Convert the test framework to use Jest instead of mocha. You can copy the config from any of the folders in `packages` or `apps`
- Update `validate-secret-scan.yaml` file in GitHub workflows to upload the coverage data. You can refer how this is done from the other validation yaml files.
- Add a flag named `secret-scan` in `codecov,yml` in the root

**Comment by Souvik9205** [comment]
Hey @rajdip-b, I would like to work on it, can you assign it to me?

**Comment by rajdip-b** [comment]
Sure, you should have used `/attempt`. Assigning it to you anyways haha.
