### ISSUE TITLE
DOCS: Add pictures to Bruno setup

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#526]
## Description

We have just migrated from using Postman to Bruno. We would like to add pictorial representation of setting up Bruno. 

You can find the PR [here](https://github.com/keyshade-xyz/keyshade/pull/525), and the hosted docs page in [here](https://docs.keyshade.xyz/contributing-to-keyshade/running-things-locally/api-testing).

**Comment by vr-varad** [comment]
hey @rajdip-b I would like to work on this issue

**Comment by rajdip-b** [comment]
Sure! Go ahead!
