### ISSUE TITLE
chore: Update turbo to latest version

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#542]
## Description

![image](https://github.com/user-attachments/assets/6bb55d59-4ae3-43a0-a378-99cf01b11c12)

Update turbo to use the latest version. Ensure that it doesn't break any of the scripts.

**Comment by yetanotheraryan** [comment]
/attempt i'd like to work on this

**Comment by rajdip-b** [comment]
@yetanotheraryan do make sure the scripts present in the root level `package.json` execute without any errors after you make the change. Also make sure to update the `turbo.json` file to reflect the newer syntax(if any).
