### ISSUE TITLE
API: Get all memberships of user

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#550]
## Description
Refer #549

## Solution

- Add a service layer function in [`workspace.service.ts`](https://github.com/keyshade-xyz/keyshade/blob/develop/apps/api/src/workspace/service/workspace.service.ts) to return a list of workspaces where the workspaceis invited to. Each item should contain the workspace details and the invitation date. The response should also have pagination support.
- Add the endpoint in [`workspace.controller.ts`](https://github.com/keyshade-xyz/keyshade/blob/develop/apps/api/src/workspace/controller/workspace.controller.ts). The path should be `GET /api/workspace/invitations`. This should be an authenticated path.
- Add relevant tests in [`workspace.e2e.spec.ts`](https://github.com/keyshade-xyz/keyshade/blob/develop/apps/api/src/workspace/workspace.e2e.spec.ts)

**Comment by mdimado** [comment]
Hi @rajdip-b , I’m interested in working on this issue. I have experience with creating service layer functions, handling pagination in API responses, and implementing authenticated routes. I’m familiar with the tech stack and confident I can add the required functionality in workspace.service.ts and workspace.controller.ts, along with writing the necessary tests in workspace.e2e.spec.ts. Looking forward to contributing to this feature

**Comment by rajdip-b** [comment]
Hey there! Sure, go ahead and best of luck!

**Comment by rajdip-b** [comment]
Don't hesitate to reach out to us if you need any help :D

**Comment by rajdip-b** [comment]
@mdimado any updates on this?

**Comment by Souvik9205** [comment]
@mdimado Hi, if you are inactive, can I work on this issue?

**Comment by muntaxir4** [comment]
@rajdip-b isn't this similar to #404 ?

**Comment by rajdip-b** [comment]
> @rajdip-b isn't this similar to #404 ?

Yes!

**Comment by rajdip-b** [comment]
@Souvik9205 hey bro, i suggest you can take up the other sub issues for this. The API was need of the hour so we fast tracked it.
