### ISSUE TITLE
BUG: Test failure while non-member tries to access a global project 

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#575]
**Describe the bug**

Projects with access level set to `GLOBAL` should be accessible by anyone in the world. Right now, the test that covers this scenario is failing. 

**To Reproduce**
1. Go to `project.e2e.spec.ts` in `apps/api/src/project`.
2. Uncomment lines 870-886
3. Run `pnpm e2e:api`
4. Encounter the error.

**Expected behavior**
The tests should pass, and the scenario should be evaluated.

**Screenshots**
- Commented out code: 
![image](https://github.com/user-attachments/assets/6be27da4-3351-4346-834f-54dd27d567fe)
- Error while running tests: 
![image](https://github.com/user-attachments/assets/54512c47-18bc-4084-b287-3fe9f21c0836)

**Comment by muntaxir4** [comment]
Are the environments, secrets and variables accessible to any user if the project is global and the user is not a menmber of workspace?

**Comment by rajdip-b** [comment]
Yes
