### ISSUE TITLE
Update license name in `package.json`

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#6]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/keyshade-xyz/keyshade/assets/83924254/eed87c5c-1b56-4f75-acb8-7eceb5f85216)
Update the license in `package.json` to this:
![image](https://github.com/keyshade-xyz/keyshade/assets/83924254/b7b0aa20-d386-4933-a212-bfc350adc8a8)

**Comment by doomdagadiggiedahdah** [comment]
This is just writing out `"license": "MPL-2.0"` in the package.json? I'll do that

**Comment by rajdip-b** [comment]
> This is just writing out `"license": "MPL-2.0"` in the package.json? I'll do that

Much appreciated!
