### ISSUE TITLE
Remove all `await` keywords from infront of mailing functions

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#63]
## Descriptions

![image](https://github.com/keyshade-xyz/keyshade/assets/83924254/c2cc3560-b709-485f-8641-fe6ac0979fde)
We want the mails to be sent asynchronously. Adding an `await` in front of mail function blocks the thread. Remove all such occurences of `await`.

**Comment by lakshay-saini-au8** [comment]
@rajdip-b 
assign this to as it short I will do it by eod

**Comment by rajdip-b** [comment]
Yeah sure! Shouldn't take much time.
