### ISSUE TITLE
Create tests for project controller

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#68]
## Description
Create tests for `project.controller.ts`. The business logic can be found under `project.service.ts` and `project.repository.ts`. You will also need to update the `mock.repository.ts` file to make the tests work. For this, use dummy data based on `schema.prisma` and dump those dummy data under `common/mocks` folder.

**Comment by rajdip-b** [comment]
@lakshay-saini-au8 drop in a comment so i can assign this to you

**Comment by lakshay-saini-au8** [comment]
@lakshay-saini-au8 
I can start on this

**Comment by rajdip-b** [comment]
@lakshay-saini-au8 hey man, any updates?
