### ISSUE TITLE
Create module for secret

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#69]
## Description

This stays at the very core of our project. The features include:

- Creating secret under a project
- Deleting secrets
- Viewing secrets
- Auto rotate secrets
- Secret versioning
- Updating secrets
- Regenerating secrets when keys are regenerated

**Comment by lakshay-saini-au8** [comment]
@rajdip-b 
I want to work on this

**Comment by rajdip-b** [comment]
@lakshay-saini-au8 that's great!! Just do bear in mind that this will be quite challenging, so do refer to the project module if you want to know about what's what. Also, discord is the best place to discuss!!

Trust me you will be lifting a lot of load off my shoulder :D
