### ISSUE TITLE
Update Swagger docs of `api-key` module

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#86]
## Description

Follow the guidelines mentioned in #82 to add the swagger docs to the controller of `api-key` module under `apps/api/src/api-key`

**Comment by dhruvabhat24** [comment]
`/attempt`

**Comment by rajdip-b** [comment]
@dhruvabhat24 it would be just /attempt :D you need to get rid of the ``

**Comment by rajdip-b** [comment]
@dhruvabhat24 here you go!
