### ISSUE TITLE
Remove all SDKs from the `package` folder

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#92]
We have created a separate SDK repository and will be using Rust to do all the work. We won't be needing the SDK support in here. Also, remove the `Cargo.toml` and other rust specific configs from this repo

**Comment by rajdip-b** [comment]
@kriptonian1 @SRINJAYDASGUPTA-Git @Sambit003 any of you want to do this?

**Comment by SRINJAYDASGUPTA-Git** [comment]
so remove ```sdk-rust``` and `sdk-node` folder? @rajdip-b

**Comment by rajdip-b** [comment]
@SRINJAYDASGUPTA-Git and, scripts related to that in `package.json`. Also remove `Cargo.toml` file and anything that is Rust

**Comment by SRINJAYDASGUPTA-Git** [comment]
ok on it @rajdip-b

**Comment by SRINJAYDASGUPTA-Git** [comment]
should i remove the cargo lock too?

**Comment by SRINJAYDASGUPTA-Git** [comment]
@rajdip-b review the pr
