### ISSUE TITLE
Auto create admin user while API startup

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#94]
## Description

The goal here is to create an admin user when the API first starts up. 

## Solution

- Create a scheduled function in user service that runs upon startup
- Check if an admin account already exists with `admin@keyshade.xyz`
- If not, create one. 
- Make the profile activated and onboarded
- Send an email notification to the `admin@keyshade.xyz` account

**Comment by rajdip-b** [comment]
Awesome! You are crushing it!

**Comment by rajdip-b** [comment]
References:

- https://docs.nestjs.com/fundamentals/lifecycle-events#usage
- https://stackoverflow.com/questions/53479741/run-program-on-init

**Comment by HarshPatel5940** [comment]
Noted. Thank you.
