### ISSUE TITLE
API: Add RLS to models in `prisma.schema`

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#95]
## Description

![image](https://github.com/keyshade-xyz/keyshade/assets/83924254/4f2c6dd0-c6ac-4284-bcc1-1fd1463c972a)
Our current tables in supabase doesn't have RLS. We would like to enable it on all tables.

Ref - https://github.com/prisma/prisma-client-extensions/tree/main/row-level-security

**Comment by sayandeeps** [comment]
hey i can do it . if nobody is currently working on it i can put up a pull request asap

**Comment by rajdip-b** [comment]
Great @sayandeeps !!

**Comment by rajdip-b** [comment]
@sayandeeps yo ser any progress?

**Comment by Allan2000-Git** [comment]
@rajdip-b I think supabase directly provides ability to enable RLS on tables

**Comment by rajdip-b** [comment]
Ah man, this is now outdated. We are not using supabase anymore
