### ISSUE TITLE
Refactor code for creating user into a util function

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#99]
## Description

Currently, both `auth.service.ts` and `user.service.ts` has logic to create users. We would like that logic to reside in a single function inside the `common` module within a file called `create-user.ts`. 

## Solution

Scrape off lines 132-168 in `user.service.ts` and lines 157-185 in `auth.service.ts` into a function with the following signature:

```typescript
  const createUser = async (user: CreateUserDto, prisma: PrismaClient): User => {}
```

**Comment by KATTASAHAN** [comment]
would u like to have these logs?
![image](https://github.com/keyshade-xyz/keyshade/assets/65811236/dfdb5c4a-0727-4cd0-981a-fde524ec5158)

**Comment by rajdip-b** [comment]
@KATTASAHAN hey bro, I'm closing this one since it got covered in the last commit I made! Thanks for attempting it though.
